### ISSUE TITLE
Deploy artifacts on Maven Central

### ISSUE THREAD

**Issue by rombert** [OfficeDev/ews-java-api#1]
It would be great if the artifacts were deployed to Maven central, removing the need to manually build and install the project on each workstation/CI server.

**Comment by pathikrit** [comment]
Hi guys, any update on this? I can help if need be - I have deployed [projects to sonatype](https://oss.sonatype.org/content/repositories/releases/com/github/pathikrit/) before. Deploying to sonatype is quite arcane (involves manually creating an issue [like this](https://issues.sonatype.org/browse/OSSRH-10148) with them). I would recommend [bintray](http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/).

**Comment by serious6** [comment]
I am currently preparing a PR for the deployment. @pathikrit maybe we can try normal deployment first because bintray seems not to be available for free? Once @vboctor opened a ticket at sonatype ossrh we can add the missing configurations / plugins. 
Feel free to comment on the [branch I created](https://github.com/serious6/ews-java-api/tree/deployToMavenCentral) for this or create a PR on your own.

**Comment by pathikrit** [comment]
The branch looks good. Looking forward to it...

**Comment by vboctor** [comment]
I will work on the registration and keep this thread updated.

**Comment by vboctor** [comment]
I've created the request to register the project within sonatype.  It should take a couple of working days to be setup.  Once it is, I will update the thread.

**Comment by serious6** [comment]
Ref. [OSSRH Issue](https://issues.sonatype.org/browse/OSSRH-13313)

**Comment by vboctor** [comment]
We hit a groupid collision.  I'm trying to see if we can reclaim the groupid.  The discussion is on the issue linked above by @serious6 .

I suspect this is the library we are conflicting with:
https://maven-repository.com/artifact/com.microsoft.ewsjavaapi

**Comment by vboctor** [comment]
@serious6 name conflict is now resolved.  See  [OSSRH Issue](https://issues.sonatype.org/browse/OSSRH-13313) for details.

**Comment by ahaarrestad** [comment]
should we start publishing snapshots?

**Comment by itavero** [comment]
Yes, please! :)

**Comment by vboctor** [comment]
As soon as we have the work done to publish the snapshots we should do it.  @serious6 I believe had a branch for this work.

**Comment by pathikrit** [comment]
Is this deployed? I don't see it here: https://oss.sonatype.org/content/repositories/releases/com/microsoft/

**Comment by serious6** [comment]
Pinged @vboctor about this. But it will be a snapshot release. So it will not be directed to the release repo.

**Comment by pathikrit** [comment]
Ah, ok, we should see it here then https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ ?

**Comment by stolsvik** [comment]
Will it appear here then? http://mvnrepository.com/

**Comment by serious6** [comment]
@stolsvik mvnrepository.com only lists release-versions. Once version 2.0 will be a stable one it (probably) will be listed there too but have in mind that this site is only a search engine not a real repository. So we cant say anything about how long it will take until the jars are included.

**Comment by pathikrit** [comment]
If you release to sonatype, snapshots will be visible here: 
https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/

And releases here:
https://oss.sonatype.org/content/repositories/releases/com/microsoft/

I see this package in neither places. When do you plan to release either the stable or snapshot to sonatype???

**Comment by vboctor** [comment]
The ews-java-api 2.0 snapshot is now published at:
https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/

**Comment by nshowkath** [comment]
Hi ,
Could you let me know when you are planning for stable release , it helps us if in case to not use not use SNAPSHOT version one that has not been released.

Thanks,
Showkath.

**Comment by serious6** [comment]
> reopened until *stable-release* has been deployed

**Comment by serious6** [comment]
first release has been deployed -> ref. #432

**Comment by pathikrit** [comment]
:+1:
