### ISSUE TITLE
Keep getting an authentication warning

### ISSUE THREAD

**Issue by bureaquete** [OfficeDev/ews-java-api#144]
We are using a Basic authentication, but ews tries using Kerberos and thus gives a warning from HTTPAuthenticator class after each action. It is as follows; 

**NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))**

We initialize ews as follows;

```ExchangeService exchangeWebService = new ExchangeService(ExchangeWebServicesConstants.VERSION);
exchangeWebService.setCredentials(new WebCredentials(username, password, domain));
exchangeWebService.setUrl(ExchangeWebServicesConstants.EXCHANGE_WEB_SERVICE_SERVER_URL);```

How can we get rid of this warning, and stop ews from trying this type of authentication?

**Comment by rlambrechts** [comment]
bureaquete, could you verify if it works with the changes I made in: https://github.com/rlambrechts/ews-java-api

Kind regards,

**Comment by bureaquete** [comment]
@rlambrechts , that did the trick!

Thanks :+1:
