### ISSUE TITLE
Find a bug. EmailAddress.tostring() is incorrect

### ISSUE THREAD

**Issue by icezmb** [OfficeDev/ews-java-api#146]
hi.
     I have found a bug in EmailAddress class. When we want to transform a EmailAddress object to String, we get an incorrect string. Follow is the tostring code(EmailAddress class line 356):

if (null != this.getName() && this.getName().isEmpty()) {
      return this.getName() + " <" + addressPart + ">";
    } else {
      return addressPart;
    }

 "if(null != this.getName() && this.getName().isEmpty())" should be  "if(null != this.getName() && !this.getName().isEmpty())",  forget to add "!"

**Comment by ahaarrestad** [comment]
if this one is merged, then perhaps we can close the issue?
