### ISSUE TITLE
NullPointerException with jre1.8

### ISSUE THREAD

**Issue by AkerEnMadrid** [OfficeDev/ews-java-api#147]
First sorry for my English, in Eclipse when I select jre1.8 there an NullPointerException, however if i select jre7 it works fine, any suggestions? thanks and great job
![tipojava](https://cloud.githubusercontent.com/assets/10241160/5501583/c59c60b8-875d-11e4-8ace-55d3d79f2258.png)
![errormail](https://cloud.githubusercontent.com/assets/10241160/5501660/b7482438-875e-11e4-824d-aee05a6afbda.png)

**Comment by serious6** [comment]
> closed for now.
