### ISSUE TITLE
Byte[] and byte[] are used interchangeably

### ISSUE THREAD

**Issue by Noblebrown** [OfficeDev/ews-java-api#16]
In several areas of the API, byte[] and Byte[] are used interchangeably. It doesn't throw a compiler error due to the lack of generics in many places, so exceptions occur at runtime instead. While primitives and their associated objects can be used interchangeably, arrays cannot. MapiTypeConverter, MapiTypeConverterMapEntry, and UserConfigurationDictionary are culprits. I would recommend this be changed to primitive byte arrays across the board.

**Comment by ahaarrestad** [comment]
issue completed?
