### ISSUE TITLE
Requests executing slow due to Kerberos authentication. Mechanism level: Failed to find any Kerberos tgt

### ISSUE THREAD

**Issue by rlambrechts** [OfficeDev/ews-java-api#160]
Apparently when using the httpclient version 4.3.6 I got authentication failures due to negotiating which authentication method to be used. Don't know if it is dependent on  environment or not.

<dependency>
<groupId>org.apache.httpcomponents</groupId>
<artifactId>httpclient</artifactId>
<version>4.3.6</version>
</dependency>

Fixed it by editing the HttpClientWebRequest.java class
public void prepareConnection() throws EWSHttpException {
...
// added:
ArrayList<String> authPrefs = new ArrayList<String>();
      authPrefs.add(AuthSchemes.NTLM);
      rcBuilder.setTargetPreferredAuthSchemes(authPrefs).build();

....
}

**Comment by serious6** [comment]
hi @rlambrechts thanks for the suggestion. Can you create a [PR](https://help.github.com/articles/using-pull-requests/) with the mentioned changes?
