### ISSUE TITLE
Java language level in Maven pom file and IntelliJ project config don't match

### ISSUE THREAD

**Issue by evpaassen** [OfficeDev/ews-java-api#167]
The Java language level in the IntelliJ IDEA config `.idea/misc.xml` is set to `1.7.`, while Maven assumes `1.5`.

The following line is in the `pom.xml`, but it doesn't seem to do anything and I don't know where it originates from. It was in the initial commit.
```
<javaLanguage.version>1.7</javaLanguage.version>
```

**Comment by serious6** [comment]
hi @evpaassen its because the missing maven-compiler-plugin definition in `pom.xml`
```xml
[...]
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${javaLanguage.version}</source>
                    <target>${javaLanguage.version}</target>
                </configuration>
            </plugin>
[...]
```
if this would be added the compiler would be set to the specified level.
I think for detecting downgrade issues in the compiler we also should add the following to the `.travis.yml`
```xml
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk6
[...]
```
this will help us to keep track of older and newer builds.

**Comment by barisaydinoglu** [comment]
jdk 1.7 is not necessary, 1.6+ is enough for ews-java-api.

i'm currently using with jdk1.6.
i cant see a reason to update bytecode version upgrade.

**Comment by pathikrit** [comment]
I don't think we should check-in editor configs in this repo. We should add this to gitignore: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by evpaassen** [comment]
@pathikrit Please see https://www.jetbrains.com/idea/help/managing-projects-under-version-control.html. The .gitignore file you mention is correct and it does **not** exclude all IntelliJ editor configuration.
