### ISSUE TITLE
Unable to bind to recurring appointments due to date formatting

### ISSUE THREAD

**Issue by ahaarrestad** [OfficeDev/ews-java-api#169]
The date-format for the recurrence block for some of our legacy appointments have for format like 2014-06-11-5:00. The code today only sypports 2014-06-11Z.

**Comment by vboctor** [comment]
@ahaarrestad is this date parsing an issue across the board or for this specific scenario?  Is your fix going to address all similar APIs?  I haven't looked at the pull request yet.  The goal would be to have consistency on handled date formats.

**Comment by ahaarrestad** [comment]
The goal is to handle the same date-formats for recurring events as for any events. I created the pull request because of the recurring events, and that's what it fixes. But it also cleans up some of the code for parsing dates.
