### ISSUE TITLE
Question: API support for saving a PostItem with a `.msg` attachment, including creation of the `.msg` bytes?

### ISSUE THREAD

**Issue by ryandm** [OfficeDev/ews-java-api#171]
Roughly, my goal is to be able to write something like this:
````
PostItem post = new PostItem(service);
GeneritItemAttachment<PostItem> attachment =
    post.getAttachments().getItemAttachment(PostItem.class); // s:PostItem:EmailMessage: maybe?
attachment.getTItem().setBody(someBody);
attachment.getAttachments().addFileAttachment(someFileName, someBytes);
post.save(WellKnownFolderName.Inbox);
````

With the effect being: A message gets saved in the Inbox with a `.msg` format attachment. The `.msg` format attachment itself has an attachment as well as the specified body etc.

Is this possible?

**Comment by ryandm** [comment]
Sorry! I just realized this needs more detail. Updating the initial comment accordingly..

**Comment by ryandm** [comment]
Anyone know the answer to this? Or any hints as to whom/where I might ask to be able to make progress on this?

**Comment by ryandm** [comment]
(Would also appreciate a reply of the form that this isn't possible right now.)

**Comment by serious6** [comment]
maybe you can also post this on [stackoverflow](http://stackoverflow.com/) under `[ewsjavaapi]` label. Regarding your problem isn´t this just about replying/forwarding a mail?

**Comment by ryandm** [comment]
Because I haven't learned of any solution to this, I've moved on to trying other approaches. Closing.
