### ISSUE TITLE
SimpleDateFormat doesn't support timezone parsing with the character X in the pattern string

### ISSUE THREAD

**Issue by derk5008** [OfficeDev/ews-java-api#181]
I downloaded latest code and it build successfully. But when I try to connect to EWS, I still got error:

Jan 20, 2015 2:17:58 PM org.apache.http.impl.auth.HttpAuthenticator generateAuthResponse
WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: Could not load configuration file C:\WINDOWS\krb5.ini (The system cannot find the file specified))
Exception in thread "main" microsoft.exchange.webservices.data.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (401)Unauthorized

The code I am using is from "Download ZIP". I have httpclient-4.3.5, httpcore-4.3.3 in build path. And here is my client code: 
ExchangeService service = new ExchangeService(); 
		ExchangeCredentials credentials = new WebCredentials("username", "password", "myDomain"); 
		service.setCredentials(credentials);
		service.setUrl(new URI("https://ewsURL"));  
		ItemView view = new ItemView(5);  
		FindItemsResults<Item> findResults = service.findItems(WellKnownFolderName.Inbox, view);	

Could anyone give some suggestion? I really appreciate it! Thanks a lot in advance!

**Comment by avromf** [comment]
Hi,

In the past, I have found the following website useful when trying to test connections to EWS.
https://testconnectivity.microsoft.com/
Select "Service Account Access (Developers)" under "Microsoft Exchange Web Services Connectivity Tests".
This lets you know whether it is a general connection problem vs. a EWS Java API problem.

**Comment by derk5008** [comment]
Hey, avromf, thank you very much! The Test couldn't go through, but I think the reason could be the firewall: my EWS is behind the firewall so it can't be reached from outside....But thanks a lot for the tips. It gives me one more way to test.

**Comment by derk5008** [comment]
OK...Got some update. I rebuild the code and my project, then the precious error is gone. But now I have following error:

Jan 20, 2015 3:18:34 PM org.apache.http.impl.auth.HttpAuthenticator generateAuthResponse
WARNING: NEGOTIATE authentication error: Invalid name provided (Mechanism level: Could not load configuration file C:\WINDOWS\krb5.ini (The system cannot find the file specified))
Exception in thread "main" microsoft.exchange.webservices.data.ServiceRequestException: The request failed. Illegal pattern character 'X'

Feel it is from DateTimeParser, but not sure...Anyone has any suggestions? Thanks a lot!

**Comment by derk5008** [comment]
Well...seems I got it figured out....That Character 'x' can't be recognized by Java 1.6. Have to change it to 'z'

**Comment by evpaassen** [comment]
It looks like this might be caused by the changes introduced in #176. Turns out that with Java 1.6, `SimpleDateFormat` doesn't support timezone parsing with the character `X` in the pattern string. I'll try to create a pull request soon.

In the meantime, you could try to use the code from revision b7e8a656598f6d9cc6db6dc12d6e5720d76bc3ae and see if that solves the problem. That would be valuable feedback.

**Comment by derk5008** [comment]
Hey, evpasssen...thanks a lot! You are right! I am using Java 1.6. The only thing I do is just replace the "x" with "z" in DateTimeParser, and then it works perfectly. I havn't had chance try the code from revision  b7e8a65  yet. Once I tried it, I will post result! Thank you so very much!

**Comment by evpaassen** [comment]
@derk5008 Changing the `X` to a `z` will most probably cause issues with different timezone formats which are supported too. But I'll look it to it.

**Comment by derk5008** [comment]
Thanks a lot, @evpaassen. One more question, are  "X" and "Z" only characters which represent timezone in Datetimeformat?

**Comment by evpaassen** [comment]
@derk5008 They both represent timezones, but in different formats. There's `X`, `z` and `Z` (but `X` does not exist in Java 6, though).

*See the documentation of SimpleDateFormat*
* Java 6: http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
* Java 7: http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html

**Comment by derk5008** [comment]
Thanks a lot, folks.. That's huge help. I think I can close this issue.

**Comment by evpaassen** [comment]
Could you please reopen this issue? The fix hasn't made it to master yet (it isn't accepted yet). When it does, this issue will be closed automatically.

**Comment by rntgrt** [comment]
can someone please help me?
how can i put this:<TimeZoneContext><TimeZoneDefinition Id=""/></TimeZoneContext>

**Comment by rntgrt** [comment]
TimeConeContext&TimeZoneDefinition in the Soap Header?
