### ISSUE TITLE
Create GitHub - Landing Page

### ISSUE THREAD

**Issue by serious6** [OfficeDev/ews-java-api#191]
I was wondering if it could be a good idea to create a [github-page](https://pages.github.com/). For giving a short introdution and to realize a some kind of landing page for visitors. Here github.io provides an easy way to achieve this.

**Comment by vboctor** [comment]
Agreed.

**Comment by vbauer** [comment]
:+1:

**Comment by serious6** [comment]
@vboctor you are the only one who can create the page. I dont have permissions to do so.

**Comment by vboctor** [comment]
I've checked-in the template site to the gh-pages branch with one of github templates (via page generator).

The page is at the following URL:
http://officedev.github.io/ews-java-api/

**Comment by serious6** [comment]
:+1:
