### ISSUE TITLE
Remove abstract prefix from interface definition (was Problems compiling in newer java version)

### ISSUE THREAD

**Issue by ahaarrestad** [OfficeDev/ews-java-api#197]
Found that the iLazyMember interface was prefixed with "abstract". This is redundant and caused some problems compiling the project in newer java versions. PullRequest #194 has a fix for the problem

**Comment by serious6** [comment]
What kind of problems are you facing?

**Comment by ahaarrestad** [comment]
It claimed that there was no method to override when in the inline implementations of the class. Disappeared when I removed the redundant "abstract". It's a small and no-risk merge anyhow :-)
