### ISSUE TITLE
Add support for millisecond formats

### ISSUE THREAD

**Issue by pathikrit** [OfficeDev/ews-java-api#206]
I get this stack trace for a valid entry in Exchange:

```
Date String 9999-12-30T23:59:59.9999999Z not in valid UTC/local format
microsoft.exchange.webservices.data.util.DateTimeParser.parseInternal(DateTimeParser.java:85)
microsoft.exchange.webservices.data.util.DateTimeParser.convertDateTimeStringToDate(DateTimeParser.java:47)
microsoft.exchange.webservices.data.EwsServiceXmlReader.readElementValueAsDateTime(EwsServiceXmlReader.java:128)
microsoft.exchange.webservices.data.GetPasswordExpirationDateResponse.readElementsFromXml(GetPasswordExpirationDateResponse.java:32)
microsoft.exchange.webservices.data.ServiceResponse.loadFromXml(ServiceResponse.java:109)
microsoft.exchange.webservices.data.GetPasswordExpirationDateRequest.parseResponse(GetPasswordExpirationDateRequest.java:61)
microsoft.exchange.webservices.data.ServiceRequestBase.readResponse(ServiceRequestBase.java:388)
microsoft.exchange.webservices.data.SimpleServiceRequestBase.readResponse(SimpleServiceRequestBase.java:163)
microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:47)
microsoft.exchange.webservices.data.GetPasswordExpirationDateRequest.execute(GetPasswordExpirationDateRequest.java:80)
microsoft.exchange.webservices.data.ExchangeService.getPasswordExpirationDate(ExchangeService.java:1622)
```

**Comment by PaulThorne** [comment]
This would be nice. I've got a program that relies on modified times to sync items, but I've noticed that EWS only transmits down to seconds, not hundredths or milliseconds. I don't know if its the fault of EWS itself, or the ews-java-api. But if milliseconds come over the wire, it'd be nice to include them. As it is, I need to do a best guess to the closest second check :/

**Comment by pathikrit** [comment]
This got broken when they moved from java date formatters to joda ones. I think they need to add the millisecond one here: https://github.com/OfficeDev/ews-java-api/blob/cf42b78594fa7f4aa2b70bf2f9c17801f8feead3/src/main/java/microsoft/exchange/webservices/data/util/DateTimeParser.java#L24
```
DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ").withZoneUTC(),
```

**Comment by ahaarrestad** [comment]
The string in question looks to be a bit in the future? (9999-12-30T23:59:59.9999999Z) is it correct or are there other bugs as well?

**Comment by pathikrit** [comment]
Yes that's a valid entry in Exchange when you set password expiry date to inifnite/max value/never expire. In anycase, that's a legal date time value (and the max that can be represented).

**Comment by pathikrit** [comment]
But ofcourse you can repro this bug with vanilla `2014-12-30T23:59:59.9999999Z`
