### ISSUE TITLE
project contains two, inconsistent licenses

### ISSUE THREAD

**Issue by HaraldBerger** [OfficeDev/ews-java-api#216]
Which license is valid for the project?

1) OfficeDev/ews-java-api/license.txt
2) OfficeDev/ews-java-api/src/site/resources/License.docx

Please remove the unnecessary one.

**Comment by ahaarrestad** [comment]
Seems like the license.txt is the valid one, and License.docx is the old one. @vboctor should know.

**Comment by vboctor** [comment]
Correct, license.txt is the valid one.  I've submitted pull request #230 to remove the extra license.
