### ISSUE TITLE
simpleHttpConnectionManager: ExchangeServiceBase

### ISSUE THREAD

**Issue by rlambrechts** [OfficeDev/ews-java-api#218]
Actually this isn't an issue it's a question. 
Is there anywhere set how many connections the simpleHttpConnectionmanager from the ExchanegServiceBase may handle?

This link states: http://hc.apache.org/httpclient-3.x/threading.html
maxConnectionsPerHost	The maximum number of connections that will be created for any particular HostConfiguration. Defaults to 2.
maxTotalConnections	The maximum number of active connections. Defaults to 20.

Which seems to me a little bit on the lower side performance wise.

**Comment by MikeN123** [comment]
The `ExchangeService` class is not thread-safe, so you should simply create more of them if you want more connections. Using more connections from 1 thread is not going to 'magically' increase the performance. The latest code uses HttpComponents 4, and the `BasicHttpClientConnectionManager`, which only creates 1 connection.
