### ISSUE TITLE
Are there any way we can retrieve UID of each Appointment or Email we created?

### ISSUE THREAD

**Issue by derk5008** [OfficeDev/ews-java-api#219]
I think this is more like a question than an "issue". I was wondering are there any way that we can return the Unique ID of each appointment that we just created? Is it possible that UID already existed in some response? Any suggestions are highly appreciated! Thank you very much!

**Comment by Noblebrown** [comment]
Not within the save action, at least not to my knowledge. You'd need to make a second call to Exchange and retrieve it as an extended property after each creation.

**Comment by derk5008** [comment]
Thanks a lot, @Noblebrown! If I make second call, how can we know we are retrieving the UID of the appointment that we just created? Seems there are no way we could know that we are retrieving the right appointment. :-(

**Comment by Noblebrown** [comment]
You still have the Appointment object when you create it, only now it has an ItemId loaded as well. You can simply use Appointment.load(PropertySet) after the create to retrieve the UID. If you're concerned about excessive calls, you could put them into a collection until they go over a certain threshhold, then use ExchangeService.loadPropertiesForItems(Iterable<Item>, PropertySet) to load the UID into all of them in a single call.
