### ISSUE TITLE
Api's to get Meeting rooms on exchange server

### ISSUE THREAD

**Issue by shubhapp** [OfficeDev/ews-java-api#220]
Does ews-java-api supports meeting room Api's if yes can any one point me to those api's if not is there any plan to support these in near future.

**Comment by jimdunkerton** [comment]
Start with ExchangeService.getRoomLists() and ExchangeService.getRooms().

A room is represented by an email address and can be treated in a similar fashion to a human user, in that you can get free/busy data and invite them to a meeting.

**Comment by shubhapp** [comment]
Thanks @jimdunkerton
