### ISSUE TITLE
Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin

### ISSUE THREAD

**Issue by shahharshj** [OfficeDev/ews-java-api#225]
Hi Everyone,
I downloaded the ews-java-api-master.zip and trying to make jar out of it using Maven tool, when I do this I am getting some Unresolved Dependencies exception as below,
************************
C:\Development\CliqueIT\ews-java-api-master\ews-java-api-master>mvn install
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.5/nexus-staging-maven-plugin-1.6.5.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.microsoft.ews-java-api:ews-java-api:2.0-SNAPSHOT (C:\Development\CliqueIT\ews-java-api-master\ews-java-api-master\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5 or one of its dependencies could not be resolved: Failed to collect dependencies for or
epo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out: connect -> [Help 2]
***************************

Did anybody faced this problem and know how to fix it?
or else is there any other place I can directly get the ews-java-api-master project Jar file.

Thanks,
-Harsh.

**Comment by serious6** [comment]
hi @shahharshj looks like you can't reach the central repo. Think you should have your proxy-settings configured. Maybe you can have a look [here](http://stackoverflow.com/questions/1251192/how-do-i-use-maven-through-a-proxy)
