### ISSUE TITLE
EwsUtilities.getPrintableTypeName() is completely broken

### ISSUE THREAD

**Issue by Noblebrown** [OfficeDev/ews-java-api#23]
It appears that EwsUtilities.getPrintableTypeName() is supposed to nicely print "List<Class>" instead of the usual debug output, but it winds up throwing Exceptions instead. I'm not even going to try describing what this method was attempting to reach this goal, but needless to say, it doesn't work at all. Either this should be implemented correctly if possible or removed entirely.

**Comment by ahaarrestad** [comment]
From what I see, it is only used in two errormessages. And yes. it seems to be completely broken. I'll have a look at it.

**Comment by serious6** [comment]
+1 for complete deletion of this **thing** since it seems to do a lot of expensive work for only one simple message. Maybe we can just think of another suitable error-message?
