### ISSUE TITLE
Bad conditional in ExtendedPropertyCollection.tryGetValue()

### ISSUE THREAD

**Issue by Noblebrown** [OfficeDev/ews-java-api#24]
In ExtendedPropertyCollection.tryGetValue(Class<T>, ExtendedPropertyDefinition, OutParam<T>), there is a conditional to see if the passed Class<T> argument is assignable from the passed ExtendedPropertyDefinition.getType(). The conditional is backward. It will throw an Exception if it is assignable and will set the value in the passed OutParam if it is not. It should be the opposite, throwing the Exception if it is NOT assignable and setting the value in the OutParam if it IS assignable.

**Comment by amille44420** [comment]
Hi all,

I see that issue is dated from September 2, I'm still having this issue today.

**Comment by serious6** [comment]
@amille44420 thanks for the report. Feel free to pass in a [PR](https://help.github.com/articles/using-pull-requests) as this is community driven piece of software.

**Comment by milkboy** [comment]
was fixed in 22206b7b6518bca2f845f8af050a68cc26507005
