### ISSUE TITLE
StreamingSubscription: reconnect after timeout

### ISSUE THREAD

**Issue by bazhiv** [OfficeDev/ews-java-api#249]
Hello 
I'm trying to synchronize my application with Calendar using Streaming Subscribtion 
My code:

 try {
			WellKnownFolderName sd = WellKnownFolderName.Calendar;
			FolderId folderId = new FolderId(sd);
			List<FolderId> folder = new ArrayList<FolderId>();
			folder.add(folderId);
            ExchangeService exchangeService = new ExchangeService();
            exchangeService.setTraceEnabled(true);
            ExchangeCredentials credentials = new WebCredentials(login, password);
            exchangeService.setCredentials(credentials);
            exchangeService.setUrl(new URI(url));

            StreamingSubscription subscription = exchangeService.subscribeToStreamingNotifications(folder,
                    EventType.Copied,
                    EventType.Created,
                    EventType.Deleted,
                    EventType.FreeBusyChanged,
                    EventType.Modified,
                    EventType.Moved,
                    EventType.NewMail
            );
            StreamingSubscriptionConnection conn = new StreamingSubscriptionConnection(exchangeService, 1);
            conn.addSubscription(subscription);

            conn.addOnNotificationEvent(new StreamingSubscriptionConnection.INotificationEventDelegate() {
                @Override
                public void notificationEventDelegate(Object sender, NotificationEventArgs args) {
                    logger.debug("==== hi notification event==========");
                    for (NotificationEvent event : args.getEvents()) {
                        if (event instanceof FolderEvent) {
                            FolderEvent folderEvent = (FolderEvent) event;
                            logger.debug("folder event: " + folderEvent.toString());
                        } else if (event instanceof ItemEvent) {						
                            ItemEvent itemEvent = (ItemEvent) event;
                            logger.debug("type: " + event.getEventType() + ", id: " + itemEvent.getItemId() );
                        } else {
                            logger.error("Unsupported event : " + event.getClass());
                        }
                    }
                }
            });
            conn.addOnDisconnect(new StreamingSubscriptionConnection.ISubscriptionErrorDelegate() {
                @Override
                public void subscriptionErrorDelegate(Object sender, SubscriptionErrorEventArgs args) {
                    //Cast the sender as a StreamingSubscriptionConnection object.
					logger.debug("The connection to the subscription is disconnected.");
                    try {
                        StreamingSubscriptionConnection connection = (StreamingSubscriptionConnection) sender;
						connection.open();
                    } catch (Exception e) {
                        logger.error(e);
                    }
				}
            });
            conn.addOnSubscriptionError(new StreamingSubscriptionConnection.ISubscriptionErrorDelegate() {
                @Override
                public void subscriptionErrorDelegate(Object sender, SubscriptionErrorEventArgs args) {
                    logger.debug("error!!");
                    if (args.getException() != null) {
                        logger.error(args.getException());
                    }
                }
            });
            conn.open();
        } catch (Exception e) {
            logger.error(e.getMessage());
        }

After timeout (1 min) EWS calls onDisconnect listeners where i try to rescoonect usiong existing connection (like in msdn article https://msdn.microsoft.com/en-us/library/hh312849(v=exchg.140).aspx) but then i get sunscribtionError - microsoft.exchange.webservices.data.ServiceResponseException: The specified subscription was not found.
All my logs:
disconnected!
The connection to the subscription is disconnected.
error!!
microsoft.exchange.webservices.data.ServiceResponseException: The specified subscription was not found.
disconnected!
The connection to the subscription is disconnected.
microsoft.exchange.webservices.data.ServiceLocalException: You must add at least one subscription to this connection before it can be opened.

So, how should i reconnect correctly?

One more question: i found that subscribtion doesn't work withous the following code
            exchangeService.setTraceEnabled(true);
Why is it mandatory?

**Comment by serious6** [comment]
@bazhiv so everything is working if you set your trace to be enabled? If that's true I would call bug on this one. Are you also using the latest version of ews-java-api?

**Comment by bazhiv** [comment]
I used a version built from master brunch about month ago. 
After update from master it everything works ok.
