### ISSUE TITLE
Define a logging strategy

### ISSUE THREAD

**Issue by Nowheresly** [OfficeDev/ews-java-api#267]
In several classes, we can find statements such as:
System.out.println("something");
ex.printStackTrace();

These statements should be replaced with some logging statements such as
LOG.info("something");
LOG.error(ex);

Basically, in java we have 3 different logging facades:
- java.util.logging (jul)
- jakarta commons logging (jcl)
- simple logging for java (slf4j)

- jul has the advantage of being included in java core library. Unfortunately, most developers think this api is useless and not very flexible.
- jcl is, by far, one of the most popular logging library. It is already a dependency of ews-java-api! Its main drawback is its rather old API that does not leverage java 5+ features (such as var args).
- slf4j is now very popular as well. It provides several bridges so that it can be used with almost any other logging facades (such as jcl for example). It leverages java 5+. So instead of writing:
```
if(LOG.isDebugEnabled()) {
  LOG.debug("foo "+bar);
}
```
we can directly write:
```
LOG.debug("foo {}", bar);
```
In the first snippet, since the arguments are evaluated before executing the method, the runtime is generating a string that would never be used if the logging level is higher than debug. To avoid such overhead, developers have no choice but to add this ugly if statement.
In the second snippet, leveraging var args, no need to add an if statement, the string will be created only if the log level is debug.

I opened this issue so that we can decide if we want to use a logging framework and if yes, which one we want to use.
My reference goes to slf4j for its efficience & flexibility.
Any thoughts ?
(Of course I'm ready to do a PR for this issue)

**Comment by evpaassen** [comment]
We're already using commons-logging in some places (see #40), like you said. I agree SLF4J is more sophisticated, but it's easier to use a library with JCL in a SLF4J application (with a bridge) than the other way around. (Please correct me if I'm wrong).

So I think it'd be better to stick with commons-logging for now.

**Comment by Nowheresly** [comment]
> it's easier to use a library with JCL in a SLF4J application (with a bridge) than the other way around. 

Well, no I don't fully agree.
Let's see in detail both cases:

Case 1. *ews-java-api uses internally jcl, but the application uses slf4j*
in the `pom.xml` file, the application needs to add as dependencies:
* `slf4j-api` (of course, the application is using it)
* `jcl-over-slf4j` : this jar contains the very same public API as jcl, but the implementation is redirecting to slf4j
* `commons-logging` must *NOT* be added as dependency

Case 2. *ews-java-api uses slf4j internally, but the application uses jcl*
in the `pom.xml` file, the application needs to add as dependencies:
* `commons-logging` (of course, the application is using it)
* `slf4j-api`: because it is a required dependency of ews-java-api
* `slf4j-jcl`: a binding that will delegate all slf4j logging calls to jcl

Everything is clearly explained [here](http://www.slf4j.org/legacy.html).

So as you can see, there's no real difficulties in any cases. We just have to choose the right dependency (which is accordingly, not always easy until we read carefully the slf4j documentation - for example declaring both dependencies jcl-over-slf4j and slf4j-jcl is a very common beginner mistake that leads to infinite loop for obvious reasons).

In case my explanations are not clear, please let me known.

**Comment by serious6** [comment]
what about using [logback](http://logback.qos.ch/reasonsToSwitch.html) and slf4j as facade? I therefore had only good experiences with this combination. And it's quite good to handle.

**Comment by evpaassen** [comment]
OK, thanks for correcting me. I didn't know of the `slf4j-jcl` bridge yet.

In case 2, however, the application pom.xml wouldn't need to define `slf4j-api` as a dependency, but the ews-java-api library would.

> what about using logback and slf4j as facade? I therefore had only good experiences with this combination. And it's quite good to handle.

We wouldn't need logback in this case, just the SLF4J facade. If someone would like to use logback (what I'd recommend), he could do so just by including logback in the application dependencies.

**Comment by Nowheresly** [comment]
I do recommand using logback as well!
I just made a PR using slf4j a logging facade.
`slf4j-api` and `jcl-over-slf4j` are now added as dependencies.
`commons-logging` is explicitly excluded.
`logback-classic` has been added with a test scope so that, when we run test, we can see the output of log statements. I put the logback configuration in `logback-test.xml`.
Please take time to review and give me your feedback.

**Comment by Nowheresly** [comment]
In case PR #275 is accepted, we could probably replace the enum `TraceFlags`with regular slf4j Marker.
And probably ExchangeServiceBase.traceXXX() methods can be adapted to leverage slf4j...
I have to investigate it.
