### ISSUE TITLE
OAuth with EWS Java APIs

### ISSUE THREAD

**Issue by nshowkath** [OfficeDev/ews-java-api#284]
Hi ,

We found there is Limitation in EWS Java APIs: EWS Java APIs that we download from https://github.com/OfficeDev/ews-java-api only Support EWS features till Exchange2010_SP2, it does have any special classes to pass OAuth token. EWS Managed APIs for .net has the Microsoft.Exchange.WebServices.Data.OAuthCredentials class through which we can pass OAuth token but till now EWS Managed Java APIs has not provided that class.

So, we need to pass OAuth token as authorization header. 
Also, when I tried passing “Bearer” type OAuth token as authorization header, service.getHttpHeaders().put("Authorization", "Bearer <token>"); but it gave me error saying "The request failed. HTTP header 'Authorization=Bearer <token>' isn't permitted. Only HTTP headers with the 'X-' prefix are permitted." 
How this limitation was resolved?
Because EWS Java API code is open source, We made some changes in the code, so they are now allowing OAuth bearer tokens as authorization header. 
We simply commented out the validate() method code in ExchangeServiceBase.java class, which was doing check for HTTP headers to be with ‘X-’ prefix and was not allowing ‘bearer’ type token to pass.
Now, we can pass OAuth token as,
service.getHttpHeaders().put("Authorization", "Bearer <token>");
--------------------------------------------------------------------------------------------------------------
Could someone from you team make this changes or   you can suggest any other solution.

Thanks & Regards,
Showkath.

**Comment by serious6** [comment]
@nshowkath thanks for the given input. Maybe just commenting out the validation process might not be the best solution for this problem. At some point we should see differences between the ews-managed-api and ews-java-api and show up the points we should have implemented in both of them (regarding "costs" and the timeline).

**Comment by nshowkath** [comment]
Hi,

Thanks for your reply , could you let me know when can we expect this change in EWS JAVA  API 

Thanks,
Showkath.

**Comment by serious6** [comment]
@nshowkath see #288 for details. But this will depend on the number of PR coming in.

**Comment by nshowkath** [comment]
Thanks , It would be great if your team get it done , otherwise we need to include your source code as part of our limitation which will causes future problem when your team implemented any new feature.
Please let me know if your need more inputs on this issue.

Thanks,
Showkath.

**Comment by vboctor** [comment]
I did look into this and noticed that when this validation was added it was mainly motivated by the need to add an X- header.  I also checked ews-managed-api latest code of [ExchangeServiceBase](https://github.com/OfficeDev/ews-managed-api/blob/master/Core/ExchangeServiceBase.cs) no longer has this check.  Digging into the history, the check was removed on 2012-MAR-20.

So I suggest removing the check within the validate method to be consistent with the EWS Managed API.  This enables adding any headers including the authorization header and hence unblocking the OAuth scenario.

Then later, we can still add OAuth support as a first class feature so that users of the library don't need to provide custom headers.  This will also bring ews-java-api to parity with ews-managed-api.

@serious6 do you have concerns about such approach?
@nshowkath will this change address your concern?

**Comment by serious6** [comment]
sounds good to me :+1:

**Comment by nshowkath** [comment]
Yes , this will resolve issue, could you let me know when can we expect this change in EWS JAVA API ?

Thanks,
Showkath.

**Comment by acaride** [comment]
Hi ! 
I need to authenticate to my EWS through a  LtpaToken2 cookie .. is that possible?
My web application is running under a WebSphere that haves a Single-Sign-On configuration (SPNEGO) .. So the credentials are negotiated between the browser - the websphere - and the active directory ... and when the user is authenticated a  LtpaToken2 cookie is set into the response

Is that possible ??  Thanks !

**Comment by girish-kumar-710** [comment]
Hi All..
How to use the java ews api to authenticate an user?? Please provide me a java code. 
I have been looking for this every where and ended up asking here. Please reply at the earliest.

**Comment by Surbhidhingra** [comment]
Hi All,

I am trying to build an android app using EWS-java-api to fetch EWS data with an oAuth token using active directory authentication lib for android. similar to what is shown in this article for .net

Below is the code:

// Code to acquire token after registering the native application in Azure active directory

authenticationContext.acquireToken(<activity context>, "<resource id: copied from the manifest file tag <resourceAppId> of Azure active directory after adding permission>", "<Application id of the registered app in AAD>", "<Application Redirect URI>", email, PromptBehavior.Always, "", AuthenticationCallback);

//We receive AuthenticationResult object containing authentication token in AuthenticationCallback onSuccess method and then call an async task to fetch EWS data

ExchangeService exchangeService = new ExchangeService(); exchangeService.setTraceEnabled(true); exchangeService.getHttpHeaders().put("Authorization", "Bearer " + mAuthenticationResult.getAccessToken()); exchangeService.setUrl(URI.create("https://outlook.office365.com/EWS/Exchange.asmx"));

I am able to get oAuth token, but i am not able to receive exchange data, it gives me unauthorised and forbidden access when fetching data using below code.

CalendarFolder cf = CalendarFolder.bind(service, WellKnownFolderName.Calendar); findResults = cf.findAppointments(new CalendarView(startDate, endDate));

Also, i am not sure about the configuration i am setting up in azure portal. It would be great if you can tell how to setup Azure AD application for fetching EWS data via oAuth authentication in android.

**Comment by agileravi** [comment]
Hi @girish-kumar-710 
have you found any java code for office365 oauth using EWS or any api?
If so, can u plz share with me. Thanks.

**Comment by wulangbnu** [comment]
I can not find  "office 365 exchange online" on  add application  in Azure Active Directory when register a new application to use oauth. And only find Microsoft Graph Permissions on the new Application Registration Porta(https://apps.dev.microsoft.com). Could you tell me where can I register my app to use oauth with ews-java-api ?

**Comment by keshi87** [comment]
I am not sure if the change fixed it. I have the app-only token I got from graph.microsoft.com using the client-credentials grant flow and seems like I cannot use that for EWS API? I was able to validate that the token is passed via the wire with the Authorization header set with the token but I still get 401 unauthorized. 

Does EWS even support access tokens received from client-credentials grant flow? Please help.

**Comment by ShanavazJs** [comment]
Can anyone please tell me. Is this enough the below code will validate our user validation?

service.getHttpHeaders().put("Authorization", "Bearer ");

**Comment by samrajcse** [comment]
Yes. It will work fine. Give as like this. Generate the Access token via Oauth2.

service.getHttpHeaders().put("Authorization", "Bearer " + accessToken);

**Comment by ShanavazJs** [comment]
Thank you @samrajcse .
I have passed the username and password for a validation it is working fine.
without password will it be possible to validate the EWS by using user access token.
If the user access token is enough to validate please tell me the procedure how to get an access token?

Please help me on that.

**Comment by samrajcse** [comment]
You can follow the below steps to get the access token. We need to have
Oath2 flow to generate tokens.

https://blogs.msdn.microsoft.com/exchangedev/2014/03/25/using-oauth2-to-access-calendar-contact-and-mail-api-in-office-365-exchange-online/

Regards,
*SAMRAJ.K*

**Comment by kirit7037** [comment]
when im trying to call ews api using access token it giving error :microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. The request failed. The remote server returned an error: (401)Unauthorized

**Comment by kumbhaj** [comment]
@serious6 I am using java ews API 2.0. I am able to set the auth token like this: 
**_service.getHttpHeaders().put("Authorization", "Bearer " + token);_**
yes, I am also getting unauthorized. No matter what I do.

**Comment by victormarcus** [comment]
To avoid getting unauthorized pass scope : https://outlook.office.com/.default  not https://graph.microsoft.com/.default
