### ISSUE TITLE
Download Attachment

### ISSUE THREAD

**Issue by 1sunpengcheng** [OfficeDev/ews-java-api#285]
Hi
I want to download the attachment from the email, I use the following code

```java
for (Item item : findResults) {
			EmailMessage email = EmailMessage.bind(service, item.getId());
				email.load();
				for (Attachment it : email.getAttachments()) {
					FileAttachment iAttachment = (FileAttachment) it;
					iAttachment.load( "C:\\" + iAttachment .getName());
				}
```
the question is "FileAttachment iAttachment = (FileAttachment) it;"
 iAttachment .getName() is null

Please help me !
thanks!

**Comment by avromf** [comment]
Did you try:
    iAttachment.load();

i.e. The idea is that you should first load the attachment and then afterwards, optionally save it to a file (or stream). You should not be passing in a file path to the load method.

**Comment by serious6** [comment]
thanks @avromf. If the question isn't solved with the hints being given plz reopen.
