### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by atamer** [OfficeDev/ews-java-api#286]
What is the plan for java-ews 2.0 release date ?

**Comment by serious6** [comment]
I think we can deploy 2.0 release when #39 is closed. As a conclusion we should decide on how to deal with the following packages:
* interfaces
* enumeration
* exception

but unfortunately there is no concret date for this.

**Comment by serious6** [comment]
_ref #288_

**Comment by serious6** [comment]
ref.  #432
