### ISSUE TITLE
"Notifications" with EWS JAVA API

### ISSUE THREAD

**Issue by mohamed-ennahdi** [OfficeDev/ews-java-api#298]
Hi,

I would like to pull notifications of a specific GitHub repository, and then I opted for the EWS JAVA API.

I follow the steps in "Getting Started with the EWS JAVA API", and I follow the steps.

I am confused when it comes to explicitely specifying the email address for the URL for the ExchangeSevice object.

My first guess was using the email related to my account (I use gmail), but that doesn't work. Also, autodiscoverUrl didn't work, when using the gmail address.

Would you please let me know how to specify the right values (URL/URI) so that I can take advantage of the API?

Thank you,
Mohamed Ennahdi El Idrissi

**Comment by serious6** [comment]
I dont think gmail is offering an hosted exchange service. So using your gmail will never work with ews-java-api. As described on the welcome page this api is...
>A java client library to access Exchange web services. The API works against Office 365 Exchange Online as well as on premises Exchange.
