### ISSUE TITLE
how can i get the attendee in an appointment

### ISSUE THREAD

**Issue by baidiqingxia** [OfficeDev/ews-java-api#306]
appointment.getRequiredAttendees();
it's always be null even if i do this when save
appointment.getRequiredAttendees().add("zu@xxx.com");

**Comment by dotCipher** [comment]
I actually had a similar issue until I realized I wasn't loading the full property set (since I was only getting the base properties) which caused me to get nulls here too.

Try doing `appointment.load();`before you make the call to `appointment.getRequiredAttendees();`

**Comment by dotCipher** [comment]
@baidiqingxia did that help your issue?

**Comment by indriesergiu** [comment]
Yup, calling `load();` fixed the problem. 
Thanks
