### ISSUE TITLE
WebProxy settings are ignored

### ISSUE THREAD

**Issue by bbucko** [OfficeDev/ews-java-api#316]
When new HttpClientWebRequest is created in ExchangeServiceBase WebProxy is not passed downstream and is not used later on.

**Comment by pranjaljain** [comment]
Does this particular bug is their in EWS Java API 1.3 version also or it came only with 2.0 ?

**Comment by bbucko** [comment]
I don't know. I haven't been using 1.3.

**Comment by bbucko** [comment]
I think that this issue is caused by missing line in ExchangeServiceBase.java. Check this patch: https://gist.github.com/bbucko/1ef9e6ac2947c85db613

**Comment by pranjaljain** [comment]
Hi @serious6 ,
Is the fix for issue available in Maven repository also? If I will use maven dependency for ews-java-api snapshot 2.0 version, will this fix come along?

Regards,
Pranjal

**Comment by serious6** [comment]
As #327 has been merged the fix is already included in the latest snapshot version.

**Comment by pranjaljain** [comment]
Hi @serious6 
It seems the fix is not merged fully! The fix given by @pheenomenon in the url https://gist.github.com/bbucko/1ef9e6ac2947c85db613, I am still not able to see in the source code.
This fix is critical to us. Can you assist here?

Regards,
Pranjal

**Comment by pranjaljain** [comment]
@serious6, @pheenomenon  I checked at location https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/3.0-SNAPSHOT/
there also the fix seems to be missing.

**Comment by nshowkath** [comment]
Hi  @serious6 ,
This issues is big blocker for us for our internal testing , could you please merge the fix and  included in the latest snapshot version.

Regards,
Showkath.
