### ISSUE TITLE
Requesting Stable Version of EWSJavaAPI Jar file

### ISSUE THREAD

**Issue by nshowkath** [OfficeDev/ews-java-api#317]
Hi,

Can someone share the information on where to download 
Stable Version of EWSJavaAPI Jar file
I found jar files  from maven-repository website 
http://maven-repository.com/artifact/com.microsoft.ewsjavaapi/exchange-ws-api
 1.1.5.2 is latest version ?

Regards,
Showkath.

**Comment by evpaassen** [comment]
Please see #1.

There is no stable version at the moment. Please note that all previously release 'stable' versions (<= 1.2) are completely broken, so it would be better to use a recent 2.0 snapshot.

**Comment by serious6** [comment]
closing this as answered

**Comment by ryandm** [comment]
stable release requests are made in #1 #317 and #320 -- @serious6  how do you feel about leaving just one of these issues open so folks have a place to follow along and get notified when a stable version is released as per the team's plan?

**Comment by serious6** [comment]
@ryandm reopened #1 AS first occurrence

**Comment by serious6** [comment]
once deployed you will also get notice via gitter and maven should also give a hint about newer versions that may be used. But leaving one ticket open for this is fine.

**Comment by ryandm** [comment]
Thanks! I didn't know about gitter either, so that's a nice pointer.
