### ISSUE TITLE
ExtendedPropertyCollection.tryGetValue wrong logic

### ISSUE THREAD

**Issue by andrejusc** [OfficeDev/ews-java-api#333]
Several lines starting at Line 200 inside microsoft.exchange.webservices.data.property.complex.ExtendedPropertyCollection code seems to suggest that only in case of not assignable from one class to another exception should be thrown:

      if (cls.isAssignableFrom(propertyDefinition.getType())) {
        String errorMessage = String.format(
            "Property definition type '%s' and type parameter '%s' aren't compatible.",
            propertyDefinition.getType().getSimpleName(),
            cls.getSimpleName());
        throw new ArgumentException(errorMessage, "propertyDefinition");
      }

And I think correct logic is to have NOT condition in place at line 200, i.e.:
if (!cls.isAssignableFrom(propertyDefinition.getType())) {...

**Comment by serious6** [comment]
@andrejusc  yes, you are right. Do you want to provide a [PR](https://help.github.com/articles/using-pull-requests/) for this?

**Comment by andrejusc** [comment]
Tried to push from my Eclipse, but doing it for the first time with Git. Please let me know if you see it.

**Comment by serious6** [comment]
you can just push to your own fork of ews-java-api so please do a fork push to that and open a pullrequest here are some informations needed:
* [fork-a-repo](https://help.github.com/articles/fork-a-repo/)
* [creating-a-pull-request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by andrejusc** [comment]
I think was able to do it now - could you see by now #334 request coming and could approve it if correct?

**Comment by andrejusc** [comment]
Closing as fix now merged
