### ISSUE TITLE
EwsUtilities.PATTERN_MONTH and PATTERN_MINUTES compiles same regex into pattern

### ISSUE THREAD

**Issue by ashwin244** [OfficeDev/ews-java-api#343]
I was testing the EwsUtilities.java page, while calling the TimeSpan getXSDurationToTimeSpan(String xsDuration) function noticed - 

    
    // Month
    m = PATTERN_MONTH.matcher(xsDuration);
    LOG.debug(m.find());
    int month = 0;
    if (m.find()) {
      month = Integer.parseInt(m.group().substring(0,
          m.group().indexOf("M")));
    }

    // Minute
    m = PATTERN_MINUTES.matcher(xsDuration);
    LOG.debug(m.find());
    int minute = 0;
    if (m.find()) {
      minute = Integer.parseInt(m.group().substring(0,
          m.group().indexOf("M")));
    }

would generate the same value due to the same regular expression compiled into a pattern.
private static final Pattern PATTERN_MONTH = Pattern.compile("(\\d+)M");
private static final Pattern PATTERN_MINUTES = Pattern.compile("(\\d+)M");

Probably, one of them needs to be changed.

**Comment by vbauer** [comment]
Just want to share some information for everybody:
This patterns were used before refactoring of the `EwsUtils` class (rev.: 3afa991bd67191ce3683c041df002332c3a301b4).

**Comment by serious6** [comment]
will you provide a PR?

**Comment by itbw** [comment]
It seems to be related to #357. All time zone periods with minutes in them are parsed in a wrong way. 
* For example TimeSpan for this one ```-PT3H30M``` will be parsed as:
```
negative true
year 0
month 30
day 0
hour 3
minute 30
seconds 0
```

* The big M for months and minutes seems to be correct according to ISO 8601 and the only difference is 'T' in the middle. For example this one ```P1Y2M10DT2H30M``` is a correct Time interval.
