### ISSUE TITLE
Stable Version of EWS Java API Jar file

### ISSUE THREAD

**Issue by nshowkath** [OfficeDev/ews-java-api#346]
The discussion on this topic is related to the following issues: #1, #288,#320 

The ews-java-api 2.0 snapshot is published at:
https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/

There is no stable version at the moment , It would be great if someone inform about milestone  release dates for stable Release ?
Just an idea  if major issues fixed in ews-java-api 2.0 snapshot , please rename this version instead <version>2.0-SNAPSHOT</version> to  “ews-java-api 2.0 stable release” 
If there is any snapshot prefix  in version information it gives us impression that it is beta version and under development .

Kind Regards,
Showkath

**Comment by serious6** [comment]
plz refer to @vboctor for deployment process as he is the one with permissions.

**Comment by evpaassen** [comment]
> If there is any snapshot prefix in version information it gives us impression that it is beta version and under development .

This library **is** under development and by no means stable.

**Comment by nshowkath** [comment]
Hi ,

@vboctor, any updates on #346, can we have one call to share concerns  , the please let me know how can I reach you. 


Thanks,
Showkath.

**Comment by vboctor** [comment]
I'm in favor of getting out a 2.0 beta release unless we see blocking issues.

@evpaassen Are there specific issues listed on github that you feel should be resolved before releasing v2 beta?  If so, we should annotate them accordingly.  The goal is to have some release out there that is better than the 1.x release and is easy to consume.

**Comment by serious6** [comment]
As 2.0 is already coming  along with some huge changes I think it will be better to make some deployment asap. The benefit will be in getting even more feedback from people using the api. Of course this piece of Software will include a lot of bugs which have not even been reported in issues so far. but Holding back this release way longer is not really an Option.

**Comment by vbauer** [comment]
@serious6 :+1:

**Comment by vboctor** [comment]
We can kick off the release process by creating a branch for 2.0 release and start publishing packages from such branch on demand.  We only merge into this branch important fixes that we think should make it into 2.0.  PRs for 2.0 must be submitted against master then back ported (in full or partial/targeted fix) to 2.0, if the bug meets the bar.

As we move to on-demand packages for 2.0 branch, we should also incorporate the signing work, though we shouldn't block on that for the beta versions.

We should avoid major refactoring / re-styling work in master until 2.0 is out to keep merging simple.

**Comment by serious6** [comment]
:+1:  I like that workflow. This will allow us to provide further improvements and also work on future releases.

**Comment by nshowkath** [comment]
@vboctor, @serious6 , Kindly provide the updates on this thread #346.
Any tentative dates for stable release of this EWS Java API.

Regards,
Showkath.

**Comment by vnitin** [comment]
Yeah, it would be better if you guys can provide a release version of 2.0.
Are there any plans for the same ?

**Comment by serious6** [comment]
ref. #432

**Comment by nshowkath** [comment]
Thanks @vboctor, @serious6 and Team .
Congratulations on this release.

**Comment by vnitin** [comment]
Thanks @serious6
