### ISSUE TITLE
ExchangeServiceBase NoClassDefFoundError

### ISSUE THREAD

**Issue by garthur** [OfficeDev/ews-java-api#355]
Having a problem with exchange service base class in which the log creation fails. The error is:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	    at microsoft.exchange.webservices.data.core.ExchangeServiceBase.<clinit>(ExchangeServiceBase.java:80)

But the class is in the ExchangeService class is in the correct package in the jar and all the correct build paths are set. Anyone have any experience with this or know how to fix it?

**Comment by serious6** [comment]
You are missing the required third party libraries such as:
(Output taken from `mvn dependency:tree`)
```xml 
[INFO] com.microsoft.ews-java-api:ews-java-api:jar:2.0-SNAPSHOT
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.4.1:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.9:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] +- joda-time:joda-time:jar:2.8:compile
```

**Comment by garthur** [comment]
Sorry, new to java/maven. Do I have to include those in my project? Or in the build of the api?

**Comment by serious6** [comment]
normally maven will do this for you when you build the api. @ runtime you need to provide them manually or configure your main-project with gradle or maven for instance and add these as dependencies.
