### ISSUE TITLE
why some field of appointment are empty?

### ISSUE THREAD

**Issue by 805728578** [OfficeDev/ews-java-api#359]
I want to find all appointments,but only some field of the appointment are empty,such as appointment.getRequiredAttendees()/appointment.getResources()/appointment.getOptionalAttendees().

save code :
Appointment appointment = new Appointment(service);
appointment.setSubject("Appointment for JAVA "+formatter.format(new Date()));
appointment.setBody(MessageBody.getMessageBodyFromText("Recurrence Test Body Msg"));
appointment.setStart(startTime);
appointment.setEnd(endTime);
appointment.getRequiredAttendees().add("xxx@xx.com");
appointment.getOptionalAttendees().add("xxx@xx.com");
appointment.getResources().add(email);
appointment.save();

find code :
CalendarFolder calendar = CalendarFolder.bind(service, WellKnownFolderName.Calendar);
CalendarView view = new CalendarView(startDate, endDate);
FindItemsResults<Appointment> appointments = calendar.findAppointments(view);
for (Appointment appointment : appointments.getItems())
 {
         String emails = "";
         AttendeeCollection attendees = appointment.getRequiredAttendees();
         for (Attendee attendee : attendees) {
	emails =emails + attendee.getAddress()+"("+attendee.getResponseType()+");";
          }
          emails += "|";
          AttendeeCollection resources = appointment.getResources();
          for (Attendee attendee : resources ) {
	emails =emails + attendee.getAddress()+"("+attendee.getResponseType()+");";
          }
         emails += "|";
         AttendeeCollection attendeess = appointment.getOptionalAttendees();
          for (Attendee attendee : attendeess  ) {
	emails =emails + attendee.getAddress()+"("+attendee.getResponseType()+");";
          }
         System.out.println("emails :"+emails );
}

out result:
            ||

why it is not value?

**Comment by dutrieux** [comment]
You need after find your appointments do this : 
```java
service.loadPropertiesForItems(appointments, new PropertySet(AppointmentSchema.RequiredAttendees, AppointmentSchema.OptionalAttendees));
```

see the explaination : http://blogs.msdn.com/b/exchangedev/archive/2010/03/16/loading-properties-for-multiple-items-with-one-call-to-exchange-web-services.aspx

**Comment by serious6** [comment]
thanks @dutrieux
