### ISSUE TITLE
build breakages?

### ISSUE THREAD

**Issue by nickersd** [OfficeDev/ews-java-api#365]
Calling:         ExchangeService service = new ExchangeService();
results in: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V 

Calling: ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
results in:         java.lang.NoSuchMethodError: microsoft.exchange.webservices.data.core.ExchangeService.<init>(Lmicrosoft/exchange/webservices/data/core/enumeration/misc/ExchangeVersion;)V

calling:             folder.add(FolderId.getFolderIdFromWellKnownFolderName(WellKnownFolderName.Calendar));
 results in a similar method not found error that I can't recreate at the moment as I'm stuck on the above 2 issues.

**Comment by serious6** [comment]
Die you include all the needed runtime dependencies? AS well AS the desired versions?

**Comment by nickersd** [comment]
I'm not building.  I'm getting from this repo.  Although perhaps I should start so that I can work on a baseline.

https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/

**Comment by evpaassen** [comment]
Looks like you're missing some of the dependencies. Do you manage dependencies yourself, or do you leave that to a build tool like Maven or Gradle (which I'd recommend)? I've updated [the wiki](https://github.com/OfficeDev/ews-java-api/wiki/Getting-Started-Guide#using-the-library) with info on this topic.

**Comment by serious6** [comment]
once #340 is merged we will also have webpages that list all the needed dependencies. maybe this will make it even clearer if you dont look at our pom in the first place or if users are not that familiar with maven.

**Comment by nickersd** [comment]
We use maven and I've had exactly what's on the wiki page in the pom for about the past 3 months.  Error suddenly started yesterday, I have a feeling that it's caching in intellij but haven't pinned it down yet.  Thanks for the help.

**Comment by evpaassen** [comment]
Could you check if the dependencies listed under *External libraries* in the Project view of IntelliJ correspond with those in the ews-java-api `pom.xml`?

**Comment by nickersd** [comment]
It turned out to be the tomcat deployment using an old jar. Manually deleted it in lib and everything was fine.  Strange caching things have happened when running with intellij in my experience.  Sorry for the confusion and thanks for the help.

**Comment by m4m4n1** [comment]
I've solved this issue changing the following dependency: **From 4.3.4 to 4.5.3**

<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.4</version>
		</dependency>
<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.3</version>
		</dependency>
