### ISSUE TITLE
Does ews-java-api support Office 365 ?

### ISSUE THREAD

**Issue by Zenil** [OfficeDev/ews-java-api#366]
Hi,

Does ews-java-api support Office 365 ? If so are there any help links on how to go about using this ?

**Comment by avromf** [comment]
In top description of this API:
"The API works against Office 365 Exchange Online as well as on premises Exchange. "

Here is a 30 second guide to connect to Office265:

	ExchangeService service = new ExchangeService();
	ExchangeCredentials credentials = new WebCredentials("the@emailaddress.com", "thePassword");
	service.setCredentials(credentials);
	service.setUrl(new URI("https://outlook.office365.com/EWS/Exchange.asmx"));

**Comment by VladanKostic** [comment]
JWebServices for Exchange supports Office 365 as well as Exchange on premises.
