### ISSUE TITLE
Accessing shared calendars

### ISSUE THREAD

**Issue by sasikiran1996** [OfficeDev/ews-java-api#377]
Hi,
I would like to access calendars which are shared with me by means of their email addresses. Is there a way to do so?

Thanks.

**Comment by evpaassen** [comment]
You'll have to [bind to a folder](https://github.com/OfficeDev/ews-java-api/wiki/Getting-Started-Guide#binding-to-an-existing-folder) with the following id:
```java
FolderId id = new FolderId(WellKnownFolderName.Calendar, Mailbox.getMailboxFromString(emailAddressOfOtherUser));
```

**Comment by sasikiran1996** [comment]
@evpaassen 
I get the following error 

`microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: The SMTP address has no mailbox associated with it.` 

Is it an issue with the permissions given by shared user(Given Full Access permission in outlook)?

**Comment by serious6** [comment]
Sounds like that this E-Mail is not known on the Server.

**Comment by SeaX** [comment]
Hello everyone,
I have a related question about calendars. I have created a new Calendar myself and would like to access appointments from that particulat calendar. I named it "TestCal" and saved it in the folder :  \\<Mailbox - User Name>\Calendar.

Is it possible to browse that calendar ? and If yes please inform me how.

thanks in advanced for your help

**Comment by toddandrew** [comment]
There is a working example here: [http://stackoverflow.com/questions/30594319/office365-api-admin-accessing-another-users-rooms-calendar-events](url). It contains a Java EWS API class that gets a room resource calendar.
