### ISSUE TITLE
Autodiscover not working in EWS Java API using OAuth

### ISSUE THREAD

**Issue by pranjaljain** [OfficeDev/ews-java-api#379]
I am facing an issue with EWS OAuth,. I got oauth2 authorization token and trying to do:

    service.getHttpHeaders().put("Authorization", "Bearer <token>");
    service.autodiscoverUrl("<email id>", new RedirectionUrlCallback());
and I get this error: microsoft.exchange.webservices.data.autodiscover.exception.AutodiscoverLocalException: The Autodiscover service couldn't be located.

**Comment by serious6** [comment]
I dont know if this is really a bug. Maybe your server is just not responding or blocks autodiscover? @nshowkath do you have any hints regarding OAUTH? _ref. #284_

**Comment by mikebell90** [comment]
OAuth has it's own discovery process if you are talking about Office365 OAuth. You don't use EWS autodiscovery at all. And for Office365 the same EWS endpoint is always used.
