### ISSUE TITLE
StringBuilder gives null pointer in appointment subject ...

### ISSUE THREAD

**Issue by softashu** [OfficeDev/ews-java-api#388]
final Appointment appointment = new Appointment(myservice);
final StringBuilder subjectMsg = new StringBuilder("hi");
appointment.setSubject(subjectMsg);

on saving 
its  gives null pointer exception

Thanks
Ashu

**Comment by serious6** [comment]
Use a simple string instead.

**Comment by softashu** [comment]
Hi

We are facing timezone issue with ExchangeService service = new
ExchangeService(ExchangeVersion.Exchange2007_SP1);

This issue not present with 2010, but we could not use 2010.

Details of Issue
------------------------
A) with Time zone setting

1. Appointment appointment = new Appointment(service);

        appointment.setStartTimeZone(new TimeZoneDefinition(){{

            setName( "India Standard Time" );
        }});


2. on save

microsoft.exchange.webservices.data.ServiceLocalException: The time zone
definition is invalid or unsupported.

                at
microsoft.exchange.webservices.data.TimeZoneDefinition.validate(TimeZoneDefinition.java:302)

                at
microsoft.exchange.webservices.data.PropertyBag.validatePropertyValue(PropertyBag.java:731)

                at
microsoft.exchange.webservices.data.PropertyBag.validate(PropertyBag.java:707)

                at
microsoft.exchange.webservices.data.ServiceObject.validate(ServiceObject.java:246)

                at
microsoft.exchange.webservices.data.Item.validate(Item.java:506)

                at
microsoft.exchange.webservices.data.Appointment.validate(Appointment.java:218)

                at
microsoft.exchange.webservices.data.CreateItemRequest.validate(CreateItemRequest.java:62)

                at
microsoft.exchange.webservices.data.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:710)

                at
microsoft.exchange.webservices.data.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:36)

                at
microsoft.exchange.webservices.data.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:140)

                at
microsoft.exchange.webservices.data.ExchangeService.internalCreateItems(ExchangeService.java:461)

                at
microsoft.exchange.webservices.data.ExchangeService.createItem(ExchangeService.java:530)

                at
microsoft.exchange.webservices.data.Item.internalCreate(Item.java:214)

                at
microsoft.exchange.webservices.data.Item.save(Item.java:371)

                at EWSDemo.createAppointment(EWSDemo.java:119)

                at EWSDemo.main(EWSDemo.java:56)

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)

                at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

                at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

                at java.lang.reflect.Method.invoke(Method.java:597)

                at
com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)



B)  without time zone setting


1. Appointment appointment = new Appointment(service);




2. on save see  the attachment it render two combo boxes extra  we do
not required  it




Please help me

Thanks
Ashutosh

**Comment by serious6** [comment]
There is already an issue regarding your Problem. Please query issues first.
