### ISSUE TITLE
Package organization

### ISSUE THREAD

**Issue by evpaassen** [OfficeDev/ews-java-api#39]
All 591 types in this library are located in the same package. This really doesn't help understanding how the library is organized.

**Comment by serious6** [comment]
@vboctor , @evpaassen I am currently working on a refactoring of the project hierarchie and will create a PR within the next 3 days.

**Comment by evpaassen** [comment]
OK. If possible, could you commit in small steps? That should make it easier to review.

**Comment by vboctor** [comment]
@serious6 are there certain principles or goals that we are trying to achieve with the re-organization that are worth discussing here first?  Or do you want to tackle this in the pull request directly?

I would do the package re-organization change after finishing the PR for the code style and the followup checkin to fix all code based on the new style rules.

**Comment by serious6** [comment]
I thought of 'making the api easier to understand' as the main goal. Having everything in the same package is like a mess in this case. Since we have many classes like on ews-managed-api I will take the structure from there and try a matching on our project.

**Comment by vbauer** [comment]
:+1:

**Comment by nickersd** [comment]
Possibly related to this is that I'm finding it not extensible.  I have the need to extend the various items to include our business uses, but the xml element name in the schema is not what the api expects.  Still looking into the best way to handle this....

**Comment by Noblebrown** [comment]
@nickersd, do you mean adding your own properties to the API and extending objects? If so, I don't believe this can be done directly. You may have to create your own extended properties if you're trying to add additional properties/data and handle them as such if you want to extend existing classes.

**Comment by nickersd** [comment]
@Noblebrown Yes I understand but  I've walked into an existing calendar implementation and don't have the luxury of designing from scratch so I'm looking for a more elegant way than the very hackish way that I've currently made it work.  I was thinking subclassing might  be the most elegant way but I could be wrong.

**Comment by vboctor** [comment]
:+1: for small commits and mirroring structure from EWS Managed API.

**Comment by serious6** [comment]
do you guys have any prefs on the organisation of the exceptions / enumerations packages? I just did a couple of attempts in having this refactored but enforced several problems which I am not sure on how to deal with:
* package autodiscover has multiple references in exceptions which will result in circular dependencies once the package will be torn appart on the other hand these classes also have several references in the other packages so how to deal with that?
* same with enumerations
* do you have any suggestions on splitting the exceptions / enumerations into other packages should it be like:
```txt
-\
  -core -\
             \- exception \-
                                  \- any core exceptions
            \- foo
            \- bar
  - dns -\
             \- exception \-
                                 \- any dns excpetions
          
```

**Comment by serious6** [comment]
Maybe #287 will also be helpful since it clears up imports.
