### ISSUE TITLE
FreeBusyAndSuggestions not working

### ISSUE THREAD

**Issue by ramamurari** [OfficeDev/ews-java-api#391]
Hi,

We are using the EWS Java API to get calendar services of Office 365.
 In GetUserAvailability , when the requested data is "FreeBusy" or "Suggestions", it works fine.
 But, it does not work for "FreeBusyAndSuggestions" . It gives the following error ", “The request failed. An internal server error occurred. The operation failed.” We are using EWS snapshot version 2.0. Can you please help us here

Thanks and Regards.
 Rama.

**Comment by serious6** [comment]
Do you have any more information in this? Any stacktrace? Did you try enabling the trace?

**Comment by ramamurari** [comment]
Hi ,

Stack trace is attached herewith 

7:58:40.201 [http-nio-8080-exec-7] ERROR java.lang.Throwable - microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. An internal server error occurred. The operation failed.
17:58:40.214 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
17:58:40.222 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.request.GetUserAvailabilityRequest.execute(GetUserAvailabilityRequest.java:245)
17:58:40.228 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.ExchangeService.getUserAvailability(ExchangeService.java:2649)
17:58:40.236 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.executor.domain.O365RequestExecutor.executeO365GetUserAvailability(O365RequestExecutor.java:893)
17:58:40.246 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.executor.request.RequestExecutor.executeGetUserAvailability(RequestExecutor.java:177)
17:58:40.250 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.executor.request.RequestExecutor.executeRequest(RequestExecutor.java:57)
17:58:40.254 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.handler.request.MeetingHandler.getUserAvailability(MeetingHandler.java:88)
17:58:40.257 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.handler.request.RuntimeHandler.getUserAvailability(RuntimeHandler.java:723)
17:58:40.261 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.handler.request.RuntimeHandler.handleGetUserAvailability(RuntimeHandler.java:678)
17:58:40.264 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.handler.request.RuntimeHandler.handlerRequest(RuntimeHandler.java:123)
17:58:40.267 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.platform.service.pih.service.controller.RuntimeServlet.getUserAvailability(RuntimeServlet.java:332)
17:58:40.269 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:58:40.272 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
17:58:40.274 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:58:40.276 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at java.lang.reflect.Method.invoke(Method.java:606)
17:58:40.278 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
17:58:40.280 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
17:58:40.282 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
17:58:40.284 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
17:58:40.285 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
17:58:40.286 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
17:58:40.287 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
17:58:40.288 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
17:58:40.289 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
17:58:40.291 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
17:58:40.292 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
17:58:40.293 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
17:58:40.294 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
17:58:40.296 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
17:58:40.297 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
17:58:40.298 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
17:58:40.300 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
17:58:40.302 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
17:58:40.303 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
17:58:40.305 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
17:58:40.306 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
17:58:40.308 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
17:58:40.310 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.mobile.premium.contextengine.commons.tenantconfig.filter.TenantContextFilter.doFilter(TenantContextFilter.java:43)
17:58:40.312 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
17:58:40.313 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
17:58:40.315 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
17:58:40.316 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
17:58:40.317 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
17:58:40.318 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
17:58:40.319 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
17:58:40.321 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.core.jpaas.security.auth.service.lib.AbstractAuthenticator.invoke(AbstractAuthenticator.java:205)
17:58:40.322 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
17:58:40.324 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
17:58:40.326 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.core.tenant.valve.TenantValidationValve.invokeNextValve(TenantValidationValve.java:215)
17:58:40.331 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.core.tenant.valve.TenantValidationValve.invoke(TenantValidationValve.java:94)
17:58:40.333 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.js.statistics.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:25)
17:58:40.334 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at com.sap.core.js.monitoring.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:25)
17:58:40.336 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
17:58:40.337 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
17:58:40.339 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
17:58:40.340 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
17:58:40.341 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
17:58:40.343 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
17:58:40.344 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1706)
17:58:40.345 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
17:58:40.346 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
17:58:40.347 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
17:58:40.348 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at java.lang.Thread.run(Thread.java:724)
17:58:40.349 [http-nio-8080-exec-7] ERROR java.lang.Throwable - Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: An internal server error occurred. The operation failed.
17:58:40.351 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.processWebException(ServiceRequestBase.java:548)
17:58:40.352 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:641)
17:58:40.353 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
17:58:40.354 [http-nio-8080-exec-7] ERROR java.lang.Throwable - 	... 62 more

Can you please help here?

Thanks and Regards,
Rama.

**Comment by serious6** [comment]
this indicates a Server error as said in the log. Try locking at the request/response that ews-java-api will provide.

**Comment by ramamurari** [comment]
Hi Andre,

Thanks for this wiki link on how to trace EWS request/response.
When I enabled it, I could see that request payload was the problem and once I gae proper payload, it started working.

Thanks and Regards,
Rama.
