### ISSUE TITLE
Question on "Respond with Comments" to an appointment

### ISSUE THREAD

**Issue by pheenomenon** [OfficeDev/ews-java-api#400]
If the Attendee accepts or declines an appointment/meeting request choosing the "Respond with Comments" option, then is there a way to capture these comments via EWS java api ? Could not find any other API which might help except Searching the inbox of the Sender for Accepted/Declined comments based on the Subject or Body of the sent item.
But even this approach does not work as it would rely that the Subject/Body to be unique. However in outlook I do see that the meeting responses are grouped together along with original sent item. Please see attachment. Anyone has pointers on how to get the comments on "Respond with Comments" ?
![screen shot 2015-08-10 at 3 58 30 pm](https://cloud.githubusercontent.com/assets/12173647/9186420/5e9effea-3f79-11e5-9972-83760a93e671.png)

**Comment by serious6** [comment]
see this c# code for details. This might be parsed to java [Tracking meeting responses by using EWS](https://msdn.microsoft.com/en-us/library/office/dd633669(v=exchg.80).aspx).
