### ISSUE TITLE
OAuth client credentials flow

### ISSUE THREAD

**Issue by ramamurari** [OfficeDev/ews-java-api#401]
Hi,

Can we use OAuth client credentials flow with only client id and secret instead of the client credentails flow with cleint id and private key certificate to access EWS 2.0 snapshot  APIs.
We have configured the resource as url https://outlook.office365.com/. But it gives 401-Unauthorized error. We tried to give url https://outlook.office365.com/EWS/Exchange.asmx as resource but it says invalid resource. Can you please let us know here how to proceed ?

Thanks and Regards,
Rama.

**Comment by ramamurari** [comment]
Hi,

Is the certificate mandatory for client credentials flow ?

I have made a Rest API call to my application token endpoint URL with client id and client secret and resource as "https://outlook.office365.com", I have got the access token, but with this token from a standalone java application, when I pass this in Authorization header with Bearer and this token, it gives 401 Unauthorized and when Trace is enabled, I get the following

x-ms-diagnostics : 2000010;reason="The access token is acquired using an authentication method that is too weak to allow access for this application. Presented auth strength was 1, required is 2.";error_category="insufficient_auth_strength"

When I tried to google for this insufficient auth strength, it says that X.509 certificates are mandatory, is that the way client credentials flow works ?

Please let me know.

Thanks and Regards,

Rama.

**Comment by serious6** [comment]
is this really a ews-java-api related question maybe you should post it on stackoverflow?

**Comment by ramamurari** [comment]
I have heard from msdn blogs forum that certificates are mandatory, hence closing this issue
