### ISSUE TITLE
what's the difference 2.0-SNAPSHOT and 3.0-SNAPSHOT?

### ISSUE THREAD

**Issue by 805728578** [OfficeDev/ews-java-api#411]

**Comment by vboctor** [comment]
Think of 3.0 as the bleeding edge development branch.  2.0 is the branch that we will use to release v2.0.  At this point, we mainly take bug fixes to the 2.0 branch.  Where 3.0 could take refactoring, new features, bug fixes, breaking API changes, etc.

Most users should be consuming 2.0-SNAPSHOT.
