### ISSUE TITLE
Cannot extract Contact "Alias"

### ISSUE THREAD

**Issue by reimac05** [OfficeDev/ews-java-api#427]
Hi guys,

Did I miss something or isn't it possible to extract the contact alias property?

getAlias() from the contact class returns null for all my room resources.

<a>http://stackoverflow.com/questions/32242436/retrieve-alias-using-java-ews-api</a>

I tried and searched for it in those objects I retrieved from ews:

   * NameResolution nameResolution = nameResolutionIterator.next();
   * Contact contact = nameResolution.getContact();
   * PropertyBag propertyBag = contact.getPropertyBag();
   * Collection<Object> propertiesValues = propertyBag.getProperties().values();
   * Set<PropertyDefinition> propertiesKeys = propertyBag.getProperties().keySet();

**Comment by serious6** [comment]
should be possible. Maybe this is a bug. Have you checked the request/response to your server?

**Comment by reimac05** [comment]
Solution is mentioned here.

http://stackoverflow.com/questions/32242436/retrieve-alias-using-java-ews-api

**Comment by serious6** [comment]
:+1:

**Comment by hui66** [comment]
could you tell me how to set alias for sender using java-ews-api
