### ISSUE TITLE
Failure to parse EndDateRecurrence

### ISSUE THREAD

**Issue by jimdunkerton** [OfficeDev/ews-java-api#43]
If you look at the XML response to a request for calendar items, where there is at least one item with a recurring rule, you may see a date like the following:

2014-07-07+01:00

which I have seen given as the value for the StartDate element of an EndDateRecurrence element.  An exception is thrown when trying to parse this date.

I believe it's down to the fact that the basic java.util.Date API doesn't deal well with offsets specified in this way.  Joda-Time may be a good way to go.

**Comment by ahaarrestad** [comment]
close this issue?
