### ISSUE TITLE
2.0 Full version Release Date

### ISSUE THREAD

**Issue by bah7303** [OfficeDev/ews-java-api#432]
Is there a target date for a full release of 2.0? The memory leak in the ExchangeService object of 1.2 is killing me. I have tried the draft version of 2.0 and the added ability to close the ExchangeService object fixes the problem but the failed Request 40 issue raised here (https://github.com/OfficeDev/ews-java-api/issues/371) is even more of a problem than the memory leak.

**Comment by serious6** [comment]
has been released see [oss.sonatype.org](https://oss.sonatype.org/#nexus-search;gav~com.microsoft.ews-java-api~ews-java-api~2.0~~)

**Comment by nshowkath** [comment]
Thanks @vboctor, @serious6 and Team .
Congratulations on this release.
