### ISSUE TITLE
setting web proxy in exchange service has no effect

### ISSUE THREAD

**Issue by pranjaljain** [OfficeDev/ews-java-api#433]
Hi,
While initializing ExchangeService object, I call method exchangeService.setWebProxy passing https proxy details. But, it seems internally it is not getting set finally while making http calls to EWS service.
I have replied at thread https://github.com/OfficeDev/ews-java-api/issues/316
Some fix was done their, but I am not able to see that fix in master branch code.

**Comment by serious6** [comment]
Seems this has been altered by another PR again maybe you can provide a New PR with a unit test included to guarantee this will not be missing in future

**Comment by pranjaljain** [comment]
Hi @serious6 
I have given new PR with the fix at https://github.com/OfficeDev/ews-java-api/pull/436
Can you please merge, if fine?
