### ISSUE TITLE
Cannot load file attachments

### ISSUE THREAD

**Issue by bboy79** [OfficeDev/ews-java-api#451]
Hi there,

I've been trying to get file attachments through the API, but to no avail. I always end up with the same exception, as soon as I execute the load() method from the FileAttachment class. The exception is as follows:

microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. Precondition for readText is nextEvent().getTypeEventType() == START_ELEMENT (got 4)

The cause of this exception seems to be the getElementText() method, called on EwsXmlReader.java, line 587:

buffer = Base64.decodeBase64(this.xmlReader.getElementText().toString());

After some digging, it seems that the getElementText() method is the same as the one shown here: http://grepcode.com/file/repo1.maven.org/maven2/stax/stax/1.2.0/com/bea/xml/stream/XMLEventReaderBase.java#XMLEventReaderBase.getElementText%28%29

As far as I can tell, the problem comes not from the method itself, but from it's input. Is there anything other thing that I need to do in order to make this work?

Thank you in advance

**Comment by serious6** [comment]
Is this a general problem with every attachment or with only some of them? Maybe you can also show up with some information on which server and ews-java-api version you are using.

**Comment by bboy79** [comment]
As far as I could infer, it happens when fetching .rpmsg files. The server version is 2010 .

However, I should apologize for keeping this issue open, as we had to give up on using the api and implement every request from scratch ourselves - since it is an Android app, issues regarding different OS versions were arising (apart from the well known api integration issues). Given this, the problem I described here was probably happening due to some incompatibility with Android.

I apologize once more, and thank you for your input!

Best regards

**Comment by yangjiebeijing** [comment]
i have the same problem

**Comment by yangjiebeijing** [comment]
javax.xml.stream.XMLStreamException: Precondition for readText is nextEvent().getTypeEventType() == START_ELEMENT
weblogic.xml.stax.XMLEventReaderBase.getElementText(XMLEventReaderBase.java:77) ~[com.bea.core.weblogic.stax_1.8.0.0.jar:1.8.0.0]

I use weblogic 10.3 and ews-java-api 2.0

**Comment by cmimendoza** [comment]
I Know is too late but i solve them change sax parser.
I add in weblogic-application.xml : 
 <wls:xml>
    	<wls:parser-factory>
    		<wls:saxparser-factory>
	          com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
	        </wls:saxparser-factory>
	        <wls:document-builder-factory>
	          com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
	        </wls:document-builder-factory>
	        <wls:transformer-factory>
	         com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
	        </wls:transformer-factory>
    	</wls:parser-factory>
    </wls:xml>

And add this for library errors


<wls:prefer-application-packages>
    		<wls:package-name>org.joda.*</wls:package-name>
    		<wls:package-name>org.apache.*</wls:package-name>
    </wls:prefer-application-packages>



I Use ews-java-api 2.2

**Comment by aayushi1992** [comment]
i have tried above code....but still getting same error

**Comment by aayushi1992** [comment]
javax.xml.stream.XMLStreamException: Precondition for readText is nextEvent().getTypeEventType() == START_ELEMENT
	at weblogic.xml.stax.XMLEventReaderBase.getElementText(XMLEventReaderBase.java:77)
 this error I am getting and i have used wlfullclient.jar and ews-java-api 2.2
Pls suggest me what can be done

**Comment by cmimendoza** [comment]
Sorry
I Also modify the folliging class of package microsoft.exchange.webservices.data.core
EwsServiceMultiResponseXmlReader Line 89 
EwsServiceXmlWriter Line 110 
EwsUtilities Line 560 
EwsXmlReader Line 91 

This is 
weblogic-application.xml
http://ziksys.website/ews/weblogic-application.xml

source:
http://ziksys.website/ews/microsof_srct.zip

Binary:
http://ziksys.website/ews/microsoftews.zip
