### ISSUE TITLE
Error org.apache.http.conn.ssl.AllowAllHostnameVerifier.INSTANCE when using EWS 2.0

### ISSUE THREAD

**Issue by thanhlv93** [OfficeDev/ews-java-api#457]
Hi all,
I'm using Ews 2.0 with libraries :

commons-codec-1.10.jar
commons-lang3-3.4.jar
commons-logging-1.2.jar
httpclient-4.4.1.jar
httpcore-4.4.1.jar

but when I run application ( app Android ) then exeption thrown :

java.lang.NoSuchFieldError: org.apache.http.conn.ssl.AllowAllHostnameVerifier.INSTANCE

Thanks , any solotion can help me.

**Comment by serious6** [comment]
Where are you running your application? Maybe you have conflicting jars (older Version of httpClient) in your classpath? Maybe [this](http://stackoverflow.com/questions/21864521/java-lang-nosuchfielderror-org-apache-http-message-basiclineformatter-instance/21876380#21876380) helps. Another Option could be to print out your `mvn dependency:tree`

**Comment by thanhlv93** [comment]
I using Android Studio to running my application with SDK 23 version.
I checked under : <a href="http://stackoverflow.com/questions/21864521/java-lang-nosuchfielderror-org-apache-http-message-basiclineformatter-instance/21876380#21876380">this</a> but results returned is null .

**Comment by thanhlv93** [comment]
Google removes support HTTP client on  Android 23 , so Ews  2.0 version can't using.
