### ISSUE TITLE
ClassNotFoundException: org.apache.http.ssl.SSLContexts

### ISSUE THREAD

**Issue by andrespineda23** [OfficeDev/ews-java-api#465]
Hi everybody. I'm new using EWS and i have the next problem:

java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts

anyone know how to fix it?

I'm using:

httpcore-4.3
commons-logging-1.2
httpclient-4.5.1

**Comment by avromf** [comment]
It seems that the SSLContexts class moved packages between version 4.3 and 4.4. 
See https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ssl/SSLContexts.html

EWS for Java 2.0 requires httpcore 4.4.
