### ISSUE TITLE
ExchangeVersion enum is incomplete

### ISSUE THREAD

**Issue by dankarp** [OfficeDev/ews-java-api#470]
The `ExchangeVersion` enum contains 4 values:

    public enum ExchangeVersion {
    
      // / Microsoft Exchange 2007, Service Pack 1
      /**
       * The Exchange2007_ s p1.
       */
      Exchange2007_SP1,
      // / Microsoft Exchange 2010
      /**
       * The Exchange2010.
       */
      Exchange2010,
    
      /// Microsoft Exchange 2010, Service Pack 1
      /**
       * Exchange2010_SP1.
       */
      Exchange2010_SP1,
    
      // Microsoft Exchange 2010, Service Pack 2
      /**
       * Exchange2010_SP2.
       */
      Exchange2010_SP2,
    }

But [the `RequestServerVersion` API documentation](https://msdn.microsoft.com/en-us/library/office/bb891876(v=exchg.150).aspx) lists 7 values:

    Exchange2007
    Target the schema files for the initial release version of Exchange 2007.
    
    Exchange2007_SP1
    Target the schema files for Exchange 2007 Service Pack 1 (SP1), Exchange 2007 Service Pack 2 (SP2), and Exchange 2007 Service Pack 3 (SP3).
    
    Exchange2010
    Target the schema files for Exchange 2010.
    
    Exchange2010_SP1
    Target the schema files for Exchange 2010 Service Pack 1 (SP1).
    
    Exchange2010_SP2
    Target the schema files for Exchange 2010 Service Pack 2 (SP2) and Exchange 2010 Service Pack 3 (SP3).
    
    Exchange2013
    Target the schema files for Exchange 2013.
    
    Exchange2013_SP1
    Target the schema files for Exchange 2013 Service Pack 1 (SP1).

Could we add the 3 missing enum values?

**Comment by serious6** [comment]
ews-java-api is missing the other specific Version only features. Adding the other values to the enum would be connected to implement these features within the API and should be added step by step. PR are welcome.

**Comment by serious6** [comment]
This is also duplicates #58
