### ISSUE TITLE
Java EWS Integration with a Single(Admin) User

### ISSUE THREAD

**Issue by dugenci** [OfficeDev/ews-java-api#478]
We are trying to develop an application in a program that will integrate with Exchange server. I could not see any option to get items with an administrator account. 
It would be helpfull to retrive items with a single(Admin) user to get all or specified user items.

**Comment by serious6** [comment]
try using [impersonation](https://msdn.microsoft.com/en-us/library/office/dd633680(v=exchg.80).aspx) or [delegated access](https://msdn.microsoft.com/de-de/library/office/dn641963(v=exchg.150).aspx)

**Comment by dugenci** [comment]
Thank you  [impersonation](https://msdn.microsoft.com/en-us/library/office/dd633680(v=exchg.80).aspx) worked fine for me. 
Setting up an user for impersonation check [Exchange Server 2010](https://msdn.microsoft.com/en-us/library/bb204095(EXCHG.140).aspx) or check [Exchange Server 2013](https://msdn.microsoft.com/en-us/library/office/dn722376(v=exchg.150).aspx) due to your exchange version.
