### ISSUE TITLE
Create an account with EWS Java API

### ISSUE THREAD

**Issue by andrespineda23** [OfficeDev/ews-java-api#479]
Hi.
¿Is it possible to create an account using the API? 

If it's possible can someone explain me please.

Thanks.

**Comment by serious6** [comment]
No you can't do that. Try using cmdlets instead if this fits. See some [examples](https://technet.microsoft.com/en-us/library/aa997663.aspx) for Details.

**Comment by andrespineda23** [comment]
This cmdlet is available in Exchange Server 2016? Or, is available in anothers versions (Example 2010?)
