### ISSUE TITLE
Reading of Gu_Id property from ExtendedProperty & InternetMessageHeader with FindItem EWS ( java code )

### ISSUE THREAD

**Issue by kumar2016** [OfficeDev/ews-java-api#482]
Hi all,
I am using using java code for FindItem EWS calls. Our ExchangeVersion is Exchange2010_SP2.
We have a guId property ( PropertyName="x-guId_value" ) added for all emails sent from mail boxes.  
The x-guId_value property details are : PropertyName="x-guId_value" , PropertyType="String" , Value = 90a75d3d-ee93-47fb-af84-66aab79754d3

For every email sent, this "x-guId_value" property is expected to be available 1) at Sent Items of Sender and 2) at Inbox of Receiver.
With my Java code ( added as an attachment ), I am able to read this "x-guId_value"  property from from email at Inbox of the Receiver. 
When I trace the logs, this "x-guId_value" is available under InternetMessageHeader and ExtendedFieldURI. I am reading it from InternetMessageHeader.    

When I use the same code to read the email from Sender's sent items ( by changing the mail box credentials, SmtpAddress, WellKnownFolderName), I am getting null pointer exception. In log trace, I could see this propety getting printed in ExtendedFieldURI under ExtendedProperty only and response doen't contain InternetMessageHeader. How can I read and print this x-guId_value from ExtendedFieldURI?  

If I am able to read the x-guId_value from ExtendedFieldURI under ExtendedProperty, I can use the same Java code for both Inbox and SentItems.  I am attaching my current code and trace log for reference.

Thanks
Kumar

**Comment by kumar2016** [comment]
[FindItem_SentItems.txt](https://github.com/OfficeDev/ews-java-api/files/103565/FindItem_SentItems.txt)
[Sender_SentItem_logs_git.txt](https://github.com/OfficeDev/ews-java-api/files/103566/Sender_SentItem_logs_git.txt)

**Comment by kumar2016** [comment]
[inbox_logs.txt](https://github.com/OfficeDev/ews-java-api/files/103586/inbox_logs.txt)

**Comment by kumar2016** [comment]
Java file name is: FindItem_SentItems.txt  
Logs from Sent Items of Sender is:  Sender_SentItem_logs_git.txt.     ( we can find  ExtendedProperty in logs).
Logs from Inbox of Receiver : inbox_logs  ( we can find both ExtendedProperty  and InternetMessageHeader in logs).

**Comment by 805728578** [comment]
service.loadPropertiesForItems((Iterable)inboxs, service.customInboxPropertySet());

//			inbox.setExtendedProperty(new ExtendedPropertyDefinition(DefaultExtendedPropertySet.Inbox, "x-guId_value", MapiPropertyType.String), "12,16");

service.setExtendedProperty(inbox, "x-guId_value", "1234567890");

Get results:
service.loadPropertiesForItems((Iterable)inboxs, service.customInboxPropertySet());

Object x-guId_value = service.getExtendedProperty(inbox, "x-guId_value");

**Comment by kumar2016** [comment]
Thank you. 
Now I am able to find the Gu_Id value from SentItems with the following change in my code:

FindItemsResults<Item> findResults = service.findItems(WellKnownFolderName.SentItems, view);
for (int i = 0; i < findResults.getItems().size() ; ++i) {        			
    Item item = findResults.getItems().get(i);
    item.load(propertySet);
     //   		InternetMessageHeaderCollection headers = item.getInternetMessageHeaders();           			
    OutParam<String> headers2 = new OutParam<>();     				
    if(item.getExtendedProperties().tryGetValue(String.class, extendedPropertyDefinition, headers2)){
    System.out.println(headers2.getParam());
    };
