### ISSUE TITLE
Question: How to get all the appointments in a calenar?

### ISSUE THREAD

**Issue by kiran4java** [OfficeDev/ews-java-api#488]
Hi,
I have created 2200 events (Appointments) in a calendar.
When I find the appointments, I get only 1000 events. How to go page by page and get all the events?

My Code:
ItemView iview = new ItemView(2200);
FindItemsResults<Item> foundAppointments = service
				.findItems(folderId, iview);

foundAppointments.getTotalCount() = 2200 ( this shows the total count).
foundAppointments.getItems().size() = 1000 ( this gives me only 1000).

for (Item item : foundAppointments.getItems()) {
				Appointment appt = (Appointment) item;
				writer.println("Event Name: "+ appt.getSubject() + " Event ID: " + appt.getId());
		}

I see only 1000 events.

How can I get remaining events?

Please help.

Thanks,
Kiran

**Comment by 805728578** [comment]
![exchange](https://cloud.githubusercontent.com/assets/9798724/13489815/181de62a-e164-11e5-81d1-6974c0960f0e.png)

**Comment by 805728578** [comment]
Page handled !
