### ISSUE TITLE
There are no attendies in the FindItemsResults

### ISSUE THREAD

**Issue by dimarzio** [OfficeDev/ews-java-api#516]
Searching for appointments is working well, but the attendee list is always empty. And this is not the permissions issue. If I use the same user in the outlook I can see all attendees.

CalendarFolder calendar = CalendarFolder.bind(exchangeService, new FolderId(WellKnownFolderName.Calendar, mailbox));
CalendarView viewTimeRange = new CalendarView(from.toDate(), to.toDate());
FindItemsResults<Appointment> appointments = calendar.findAppointments(viewTimeRange);

Following expression is always empty:
appointments.getItems().get(0).getRequiredAttendees()

Other information is available. Bug? Wrong API usage?

**Comment by indriesergiu** [comment]
Try calling `Appointment.load()` before querying the attendees list.

**Comment by dimarzio** [comment]
Thank you! It worked.
