### ISSUE TITLE
Error while sending email from outlook.com

### ISSUE THREAD

**Issue by anidotnet** [OfficeDev/ews-java-api#519]
I am writing some junit test cases using ews-java-api to send mails. I have setup a mail account in outlook.com and using it to send and receive mails. While sending mails, sometimes I get this below error:

> microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: An internal server error occurred. **The operation failed., WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.**
>   at microsoft.exchange.webservices.data.core.response.ServiceResponse.internalThrowIfNecessary(ServiceResponse.java:278)
>   at microsoft.exchange.webservices.data.core.response.ServiceResponse.throwIfNecessary(ServiceResponse.java:267)
>   at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:165)
>   at microsoft.exchange.webservices.data.core.ExchangeService.sendItem(ExchangeService.java:789)
>   at microsoft.exchange.webservices.data.core.service.item.EmailMessage.internalSend(EmailMessage.java:171)
>   at microsoft.exchange.webservices.data.core.service.item.EmailMessage.sendAndSaveCopy(EmailMessage.java:300)
>   at com.dizitart.orange.exchange.ExchangeConnection.sendMessage(ExchangeConnection.java:199)
>   ... 34 more

What does this error message means?

**Comment by anidotnet** [comment]
Nope. I have not.

**Comment by exp-amal** [comment]
@anidotnet  Were you able to solve it?

**Comment by anidotnet** [comment]
@exp-amal Nope.

**Comment by exp-amal** [comment]
@anidotnet  Try logging in your mail and verify it. My issue got resolved

**Comment by anidotnet** [comment]
Is there any fix for this issue? I have long ago abandoned the project where I was using it.

**Comment by exp-amal** [comment]
It is just mail verification issue. You can simply login to the outlook account which you are using. They will ask for you to confirm your identity. Something like "Help us fight spam email 
We're sorry to have to ask you to prove you're a person. Most spam comes from automated programs, which can't solve puzzles like this."

Below, there will be option to enter your phone number and confirm your identity. That's it.
