### ISSUE TITLE
Multiple Errors while sending an email

### ISSUE THREAD

**Issue by Lugo239** [OfficeDev/ews-java-api#522]
Greetings!
I am currently rotating from error one to error two and so on. I am really confused how to fix this. 
I already checked my credentials with the EWS-Editor. Everything is fine. 

Dependencies:

>  compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.3.0'
    compile 'org.altbeacon:android-beacon-library:2.7.1'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile files('libs/jcifs-1.3.15.jar')
    compile files('libs/commons-logging-1.1.1.jar')
    compile files('libs/commons-codec-1.4.jar') 
   compile('com.microsoft.ews-java-api:ews-java-api:2.0') { exclude group: 'org.apache.httpcomponents' }}

There are many different errors i can create using different versions:

1. compile'org.apache.httpcomponents:httpclient:4.5.2'
This leads into the NoClassDefFound Error (org.apache.http.client.protocol.HttpClientContext)

2. compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'
This leads into the NoClassDefFound Error (DefaultHostNameVeifier missing)

3. compile files('libs/ews.jar') 
This leads into the SendMessage Format == null error, it was a manipulated version i found on stackoverflow

I am reading tons of posts here and on stackoverlow. When i try to fix it with the i slide into another error again (like a circle). I really need your help. The access on the microsoft exchange server for meeting rooms, emails and appointments is fundamental for my application.

Any hint is welcome.

EDIT: 
`useLibrary 'org.apache.http.legacy'`

**Comment by hariso** [comment]
@Lugo239 The reason you are doing this:

`compile('com.microsoft.ews-java-api:ews-java-api:2.0') { exclude group: 'org.apache.httpcomponents' }}`

is that you are using Apache HttpClient 3.x (or older), right?

I am pretty sure you won't be able to make ews-java-api work without Apache HttpComponents, it's simply a dependency of it. I know it's not an answer, but why not consider using Apache HttpComponents in your own code? It's already at 5.x.

Disclaimer: I am an EWS newbie. However, I am working with Java all the time, and this doesn't look like something specific to EWS Java API.

**Comment by Lugo239** [comment]
Thanks for the reply @hariso ! It is working right now ;)
