### ISSUE TITLE
Create appointments with extended properties ?

### ISSUE THREAD

**Issue by andreabenini** [OfficeDev/ews-java-api#572]
Hi All,
I'm creating an appointment item with something like:

``` java
appointment.setSubject(Subject);
appointment.setBody(MessageBody.getMessageBodyFromText(Body));
appointment.setStart(startDate);
appointment.setEnd(endDate);
...
appointment.save();
```

This works and I'm happy with that, now from what I have understood from MSDN docs I can add an extended property to it with something like:

``` java
UUID MyPropertySetId = UUID.fromString("00012345-0000-0000-C000-000000012345");
ExtendedPropertyDefinition extendedPropertyDefinition = new ExtendedPropertyDefinition(MyPropertySetId, "CustomID", MapiPropertyType.String);
appointment.setExtendedProperty(extendedPropertyDefinition, CustomIDValue);
```

I have never seen some code related to appointments but I guess it could be fine for them as well as for emails, contacts and so on. I have inserted the code before the appointment.save() and no exceptions were reported with this code.

Now I cannot figure how to get my data back from the same item. I can retrieve item information with some code like:

``` java
FindItemsResults<Appointment> findResults = calFolder.findAppointments(new CalendarView(startDate, endDate));
for (Appointment appointment : findResults.getItems()) {
    appointment.load();
    System.out.println(appointment.getSubject());
    System.out.println(appointment.getLocation());
    System.out.println(appointment.getExtendedProperties().getCount()) );// Always o ???
```

`appointment.getExtendedProperties().getCount()` is **always 0**, can someone tell me why or what am I doing wrong ?

Thanks
Ben

**Comment by davster** [comment]
You need to add that prop in the CalendarView's shape so that EWS knows to return it.  By default, no extended properties are returned.  Its like a select statement in SQL - if you don't ask for it, you don't get it (ignoring * of course :))

**Comment by andreabenini** [comment]
I guess I'm missing the point somewhere, 
here's what I do for writing a new appointment
```java
public void AppointmentCreate(String Subject, Date startDate, Date endDate, String Body, String CustomID) {
	        Appointment appointment = new Appointment(Service);
	        appointment.setSubject(Subject);
	        appointment.setBody(MessageBody.getMessageBodyFromText(Body));
	        appointment.setStart(startDate);
	        appointment.setEnd(endDate);
	        if (CustomID!=null && !CustomID.isEmpty()) {
                    ExtendedPropertyDefinition extendedPropertyDefinition = new ExtendedPropertyDefinition(DefaultExtendedPropertySet.Appointment, "CustomID", MapiPropertyType.String);
                    appointment.setExtendedProperty(extendedPropertyDefinition, CustomID);
	        }
            appointment.save();
}
```
and here's what I do for retrieving appointments:
```java
void AppointmentsList(Date startDate, Date endDate) {
            PropertySet MyPropertySet = new PropertySet(BasePropertySet.FirstClassProperties);
            ExtendedPropertyDefinition extendedProperty = new ExtendedPropertyDefinition(DefaultExtendedPropertySet.Appointment, "CustomID", MapiPropertyType.String);
            MyPropertySet.add(extendedProperty);
            CalendarFolder calFolder = CalendarFolder.bind(Service, WellKnownFolderName.Calendar);
            CalendarView CalendarView = new CalendarView(startDate, endDate);
            CalendarView.setPropertySet(MyPropertySet);
            FindItemsResults<Appointment> findResults = calFolder.findAppointments(CalendarView);
            for (Appointment appointment : findResults.getItems()) {
                appointment.load();
                System.out.println(appointment.getExtendedProperties().getCount());
            }
}
```
It seems I can save my appointment but I have tried to add the new property with setPropertySet as you suggested (when reading) but I'm missing some doc or information somewhere because I still get **0** on extended properties count

What am I missing here ?
Thanks again
Ben

**Comment by andreabenini** [comment]
In the AppointmentsList() I have added the extended property to `MyPropertySet` and used it to expand `CalendarView` as written in the code above but nothing has changed, what am I missing ? Is the above function correct or is there someone doing it with calendars like me ?

**Comment by davster** [comment]
That looks correct.. Can you turn tracing on and post what the actual request XML looks like?  

Another side point, is the DefaultExtendedPropertySet.Appointment the "well known" appointment property set guid?  If so, I would advise against that.  You shouldn't create new props in another persons namespace.  Use your own if that is the case.  Ill even be nice and give you a GUID from my own personal stash:

bd61c837-13aa-4364-8a77-52ce7afecfc7

**Comment by andreabenini** [comment]
Semplified code and enabled tracing with:
```java
// here I am on connection
            Service.setTraceEnabled(true);// XXX TODO Remove
            Service.setTraceFlags(EnumSet.allOf(TraceFlags.class));
            Service.setTraceListener(new ITraceListener() {
                public void trace(String traceType, String traceMessage) {
                    System.out.println("Type:" + traceType + " Message:" + traceMessage);
                }
            });
```

...and now the code, UUID fixed as you suggested for sample purpose:
```java
    public void AppCreate(String Subject, Date startDate, Date endDate, String Body, String CustomID) {
        Appointment appointment;
        try {
            appointment = new Appointment(Service);
            appointment.setSubject(Subject);
            appointment.setBody(MessageBody.getMessageBodyFromText(Body));
            appointment.setStart(startDate);
            appointment.setEnd(endDate);
            if (CustomID!=null && !CustomID.isEmpty()) {
                    UUID MyPropertySetId = UUID.fromString("bd61c837-13aa-4364-8a77-52ce7afecfc7");
                    ExtendedPropertyDefinition extendedPropertyDefinition = new ExtendedPropertyDefinition(MyPropertySetId, "CustomID", MapiPropertyType.String);
                    appointment.setExtendedProperty(extendedPropertyDefinition, CustomID);
            }
            appointment.save();
            System.out.println("Created");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void AppList(Date startDate, Date endDate) {
        try {
            PropertySet MyPropertySet = new PropertySet(BasePropertySet.FirstClassProperties);
            UUID MyPropertySetId = UUID.fromString("bd61c837-13aa-4364-8a77-52ce7afecfc7");
            ExtendedPropertyDefinition extendedProperty = new ExtendedPropertyDefinition(MyPropertySetId, "CustomID", MapiPropertyType.String);
            MyPropertySet.add(extendedProperty);
            CalendarFolder calFolder = CalendarFolder.bind(Service, WellKnownFolderName.Calendar);
            CalendarView CalendarView = new CalendarView(startDate, endDate);
            CalendarView.setPropertySet(MyPropertySet);
            FindItemsResults<Appointment> findResults = calFolder.findAppointments(CalendarView);
            for (Appointment appointment : findResults.getItems()) {
                appointment.load();
                System.out.println("Subject=" + appointment.getSubject());
                System.out.println(appointment.getExtendedProperties().getCount());
            }
            System.out.println("Done");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

to create an appointment:
```java
Server.debugWrite("Creazione appuntamento");
        Date Now = new Date();
        Server.AppointmentCreate("Test Appointment", Now, DateUtils.addHours(Now, 1), "AB Something");
```
to list it:
```java
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date startDate = sdf.parse("2016-10-01 00:00:00");
            Date endDate   = sdf.parse("2016-10-31 23:59:59");
            Server.PrintRemoteAppointmentsList(startDate, endDate);
```

and here's the output produced (as attachment).
[ews.output.txt](https://github.com/OfficeDev/ews-java-api/files/562306/ews.output.txt)

I have looked at the trace but I really cannot figure what's wrong with it
Thanks Again
Ben

**Comment by andreabenini** [comment]
Same ews.output.txt from above but prettified in my debug session
[ews.output.txt](https://github.com/OfficeDev/ews-java-api/files/566425/ews.output.txt)
Hope it helps, I have no clues on possible error (yet)

**Comment by davster** [comment]
I just tried the raw requests from your text file and it works fine on my end.  See attached.

**Comment by davster** [comment]
Trying that again...  For some reason it isn't attaching files for me...

// request

<?xml version="1.0" encoding="utf-8"?>
  <soap:Envelope
      xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
      xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
    <soap:Header>
      <t:RequestServerVersion Version="Exchange2010_SP2"></t:RequestServerVersion>
    </soap:Header>
    <soap:Body>
      <m:FindItem Traversal="Shallow">
        <m:ItemShape>
          <t:BaseShape>AllProperties</t:BaseShape>
          <t:AdditionalProperties>
            <t:ExtendedFieldURI PropertySetId="bd61c837-13aa-4364-8a77-52ce7afecfc7" PropertyName="CustomID" PropertyType="String"></t:ExtendedFieldURI>
          </t:AdditionalProperties>
        </m:ItemShape>
        <m:CalendarView StartDate="2016-09-30T22:00:00Z" EndDate="2016-10-31T22:59:59Z"></m:CalendarView>
        <m:ParentFolderIds>
          <t:DistinguishedFolderId Id="calendar"/>
        </m:ParentFolderIds>
      </m:FindItem>
    </soap:Body>
  </soap:Envelope>

// response

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo MajorVersion="15" MinorVersion="1" MajorBuildNumber="726" MinorBuildNumber="0" Version="V2016_10_10" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:FindItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:RootFolder TotalItemsInView="1" IncludesLastItemInRange="true">
            <t:Items>
              <t:CalendarItem>
                <t:ItemId Id="AAMkADM1MGVkYTcwLTQ3YjctNGE5MC05ZDg4LTIyYzMwYTNiMDBmNgBGAAAAAAAl0DTOXI5JQoC7tXCGk6leBwDUrfWit3YtSYyCVH4UnGkpAAAAAAENAADUrfWit3YtSYyCVH4UnGkpAAAAACEfAAA=" ChangeKey="DwAAABYAAADUrfWit3YtSYyCVH4UnGkpAAAAACH/"/>
                <t:ParentFolderId Id="AAMkADM1MGVkYTcwLTQ3YjctNGE5MC05ZDg4LTIyYzMwYTNiMDBmNgAuAAAAAAAl0DTOXI5JQoC7tXCGk6leAQDUrfWit3YtSYyCVH4UnGkpAAAAAAENAAA=" ChangeKey="AQAAAA=="/>
                <t:ItemClass>IPM.Appointment</t:ItemClass>
                <t:Subject>Test Appointment</t:Subject>
                <t:Sensitivity>Normal</t:Sensitivity>
                <t:DateTimeReceived>2016-11-02T14:26:34Z</t:DateTimeReceived>
                <t:Size>3662</t:Size>
                <t:Importance>Normal</t:Importance>
                <t:IsSubmitted>false</t:IsSubmitted>
                <t:IsDraft>false</t:IsDraft>
                <t:IsFromMe>false</t:IsFromMe>
                <t:IsResend>false</t:IsResend>
                <t:IsUnmodified>false</t:IsUnmodified>
                <t:DateTimeSent>2016-11-02T14:26:34Z</t:DateTimeSent>
                <t:DateTimeCreated>2016-11-02T14:26:33Z</t:DateTimeCreated>
                <t:ReminderDueBy>2016-10-31T16:19:28Z</t:ReminderDueBy>
                <t:ReminderIsSet>true</t:ReminderIsSet>
                <t:ReminderMinutesBeforeStart>15</t:ReminderMinutesBeforeStart>
                <t:HasAttachments>false</t:HasAttachments>
                <t:ExtendedProperty>
                  <t:ExtendedFieldURI PropertySetId="bd61c837-13aa-4364-8a77-52ce7afecfc7" PropertyName="CustomID" PropertyType="String"/>
                  <t:Value>AB Something</t:Value>
                </t:ExtendedProperty>
                <t:Culture>en-US</t:Culture>
                <t:EffectiveRights>
                  <t:CreateAssociated>false</t:CreateAssociated>
                  <t:CreateContents>false</t:CreateContents>
                  <t:CreateHierarchy>false</t:CreateHierarchy>
                  <t:Delete>true</t:Delete>
                  <t:Modify>true</t:Modify>
                  <t:Read>true</t:Read>
                  <t:ViewPrivateItems>true</t:ViewPrivateItems>
                </t:EffectiveRights>
                <t:LastModifiedName>Administrator</t:LastModifiedName>
                <t:LastModifiedTime>2016-11-02T14:26:35Z</t:LastModifiedTime>
                <t:IsAssociated>false</t:IsAssociated>
                <t:WebClientReadFormQueryString>?ItemID=AAMkADM1MGVkYTcwLTQ3YjctNGE5MC05ZDg4LTIyYzMwYTNiMDBmNgBGAAAAAAAl0DTOXI5JQoC7tXCGk6leBwDUrfWit3YtSYyCVH4UnGkpAAAAAAENAADUrfWit3YtSYyCVH4UnGkpAAAAACEfAAA%3D&amp;exvsurl=1&amp;viewModel=ICalendarItemDetailsViewModelFactory</t:WebClientReadFormQueryString>
                <t:WebClientEditFormQueryString>?ItemID=AAMkADM1MGVkYTcwLTQ3YjctNGE5MC05ZDg4LTIyYzMwYTNiMDBmNgBGAAAAAAAl0DTOXI5JQoC7tXCGk6leBwDUrfWit3YtSYyCVH4UnGkpAAAAAAENAADUrfWit3YtSYyCVH4UnGkpAAAAACEfAAA%3D&amp;exvsurl=1&amp;viewModel=ComposeCalendarItemViewModelFactory</t:WebClientEditFormQueryString>
                <t:ConversationId Id="AAQkADM1MGVkYTcwLTQ3YjctNGE5MC05ZDg4LTIyYzMwYTNiMDBmNgAQANdQ6ZJUiTJFjr9B7rGg/Tg="/>
                <t:UID>040000008200E00074C5B7101A82E0080000000001F9871C1535D20100000000000000001000000056211C33164FC74181F18C11C696F2CF</t:UID>
                <t:DateTimeStamp>2016-11-02T14:26:35Z</t:DateTimeStamp>
                <t:Start>2016-10-31T16:19:28Z</t:Start>
                <t:End>2016-10-31T17:19:28Z</t:End>
                <t:IsAllDayEvent>false</t:IsAllDayEvent>
                <t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
                <t:IsMeeting>true</t:IsMeeting>
                <t:IsCancelled>false</t:IsCancelled>
                <t:IsRecurring>false</t:IsRecurring>
                <t:MeetingRequestWasSent>false</t:MeetingRequestWasSent>
                <t:IsResponseRequested>true</t:IsResponseRequested>
                <t:CalendarItemType>Single</t:CalendarItemType>
                <t:MyResponseType>Organizer</t:MyResponseType>
                <t:Organizer>
                  <t:Mailbox>
                    <t:Name>Administrator</t:Name>
                    <t:EmailAddress>...</t:EmailAddress>
                    <t:RoutingType>EX</t:RoutingType>
                    <t:MailboxType>OneOff</t:MailboxType>
                  </t:Mailbox>
                </t:Organizer>
                <t:Duration>PT1H</t:Duration>
                <t:TimeZone>UTC</t:TimeZone>
                <t:AppointmentSequenceNumber>0</t:AppointmentSequenceNumber>
                <t:AppointmentState>1</t:AppointmentState>
                <t:IsOnlineMeeting>false</t:IsOnlineMeeting>
              </t:CalendarItem>
            </t:Items>
          </m:RootFolder>
        </m:FindItemResponseMessage>
      </m:ResponseMessages>
    </m:FindItemResponse>
  </s:Body>
</s:Envelope>

**Comment by andreabenini** [comment]
Thanks davster,
I have found the problem myself and your hints/comments were really helpful to figure what's happening here. My code above works but I was focused just on the getCount() result to count ext properties inside the appointment. I have tried to figure what was going there and I have discovered something better, I have placed this for..loop inside the for...getItems() and I can see my properties:
```java
for (ExtendedProperty property :appointment.getExtendedProperties().getItems()) {
    System.out.println(property.getValue());
}
```
And I can finally see what's going on there, debug was really helpful because inside the XML trace I can see my value in the appointment insert as well as in the "select" statement.
I was just missing the point in the display because the result it's in the ExtendedPropertyCollection obtainable with the getExtendedProperties().

I have posted my solution here so others might find it helpful (hopefully) instead of wasting days on it

**Comment by zhiqiangren** [comment]
@andreabenini  Hi,Ben, I saw your example above ,i have a problem,this is ,in your method`AppointmentCreate()`,you setthe body like that `appointment.setBody(MessageBody.getMessageBodyFromText("this is the content."));`,i also set the body the same as you in my application, but when retrive the body,i write this code  `appointment.getBody()`，but I got some HTML code,show you code :  `<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="Generator" content="Microsoft Exchange Server">
		
		<style>
			
		</style>
	</head>

	<body>
		<font face="Times New Roman" size="3"><span style="font-size:12pt;"><a name="BM_BEGIN"></a><div><font face="Courier New">时间: 2018年12月29日 17:30-18:30。 ### (UTC&#43;08:00)北京，重庆，香港特别行政区，乌鲁木齐
位置: 香格里拉大饭店&nbsp; ！！！
` ,     
  `*~*~*~*~*~*~*~*~*~*<br></font></div><div>this is the content.</div></span></font>
	</body>

</html>` ,how can i only get the content "this is the content" ? Pleaseee help me .

**Comment by OS-JaR** [comment]
Hi,
this code is C# but should solve your problem...
You have to request item with plain text body style like this:

PropertySet set = new PropertySet(BasePropertySet.FirstClassProperties);
set.RequestedBodyType = BodyType.Text;

ItemView view = new ItemView(1000);
view.PropertySet = set;

FindItemsResults<Item> results = service.FindItems(WellKnownFolderName.Inbox, view);
Item item = results[0];
Console.WriteLine(item.Body);

**Comment by zhiqiangren** [comment]
@OS-JaR Thank you !i try you code, but i have two questions.
(1)this is ews-java-api,is it suitable for C#?
(2)in you code, this is C#,and you get FindItemsResults from WellKnownFolderName.Inbox,this line in you code `FindItemsResults results = service.FindItems(WellKnownFolderName.Inbox, view);` ,but i get FindItemsResults from WellKnownFolderName.Calendar.
so i try you code in java,i fail.show you whole code that i write : 

PropertySet propertity = new PropertySet(AppointmentSchema.Subject, AppointmentSchema.Organizer,

AppointmentSchema.Location, AppointmentSchema.Start, AppointmentSchema.End, AppointmentSchema.IsMeeting,
AppointmentSchema.IsAllDayEvent);

propertity.setRequestedBodyType(BodyType.Text);
CalendarView cView = new CalendarView(startDate, endDate, Integer.MAX_VALUE);
cView.setPropertySet(propertity);

FindItemsResults appointments = service.findAppointments(WellKnownFolderName.Calendar, cView);

for (Appointment appoint : appointments.getItems()) {
System.out.println(appoint.getBody());
}

one example of the result is : 
`<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Exchange Server"><style></style></head><body><font face="宋体" size="2"><span style="font-size:10.5pt;"><div align="left" style="text-align:justify;">this is the content !</div><div align="left" style="text-align:justify;"><font face="Times New Roman">&nbsp;</font></div></span></font></body></html>
`,
 i donot know where i am wrong, Please take a look at it for me ！thanks a lot .

**Comment by pkropachev** [comment]
Hello!

```java
void retrieveInfoAboutAppointments(Date startDate, Date endDate, BodyType bodyType) {
    try {
        CalendarFolder calendarFolder = CalendarFolder.bind(service, WellKnownFolderName.Calendar);
        CalendarView calendarView = new CalendarView(startDate, endDate);
        calendarView.setPropertySet(new PropertySet(BasePropertySet.IdOnly));
        FindItemsResults<Appointment> appointments = calendarFolder.findAppointments(calendarView);

        if (appointments.getItems().size() == 0) {
            System.out.println("No appointments found!");
            return;
        }

        PropertySet propertySet = new PropertySet(BasePropertySet.IdOnly,
                AppointmentSchema.Subject,
                AppointmentSchema.Body,
                AppointmentSchema.Organizer,
                AppointmentSchema.Start,
                AppointmentSchema.End);
        propertySet.setRequestedBodyType(bodyType);

        service.loadPropertiesForItems(new ArrayList<Item>(appointments.getItems()), propertySet);

        for (Appointment appointment : appointments) {
            System.out.println("Subject: " + appointment.getSubject());
            System.out.println("Body: " + appointment.getBody());
            System.out.println("Organizer: " + appointment.getOrganizer());
            System.out.println("Start: " + appointment.getStart());
            System.out.println("End: " + appointment.getEnd());
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

retrieveInfoAboutAppointments(startDate, endDate, BodyType.Text);
retrieveInfoAboutAppointments(startDate, endDate, BodyType.HTML);
```

**Comment by zhiqiangren** [comment]
@pkropachev i try your code ,i succeed,Thank you very much !
