### ISSUE TITLE
get only the latest email in a email chain

### ISSUE THREAD

**Issue by sunnykeerthi** [OfficeDev/ews-java-api#595]
I am using EWS to read email body part alone from email of inbox.

I need to extract only replied email body instead of whole email body.

```
************
Hi,

This is the latest Email

Thanks,
Your Mail

From:YourMail@gmail.com
To: ----
----------
----------

This is the first email
Regard
Admin.
************
```

So when I read email body of above email I get the whole body mentioned above. But what I need is only:

```
Hi,

This is the latest Email

Thanks,
Your Mail
```

as the above email is latest in that communication chain.

I tried using getUniqueBody(), but this results in a null pointer.

Please let me know how can I fix this.

Thanks,
Sunny

**Comment by shwetasi** [comment]
Hi Sunny,

Did you find any way to read the latest mail.
