### ISSUE TITLE
Project health

### ISSUE THREAD

**Issue by davidmoten** [OfficeDev/ews-java-api#600]
I'm lucky enough to have connected to a mailbox on o365 and downloaded emails without much hassle but when trying with `StreamingSubscription` encountered a number of problems. I notice that 

* there is only one release (AWS SDK publishes releases to Maven Central almost daily for many language platforms)

I notice that issues from last year to do with `StreamingSubscription` have not received any reaction from project maintainers so I'm wondering:

* what resources are being allocated to maintain this project?
* can we expect any improvement (attention to issues, frequent releases)?

**Comment by OS-JaR** [comment]
+1 for this questions...some news here?

**Comment by philci52** [comment]
Same here, I filed a seemingly trivial bug to fix in November and there doesn't seem to be any action on it.

**Comment by davidmoten** [comment]
I asked about this project through Microsoft internal channels and got this response:

>Microsoft Graph is our main API to access users in Office 365 and Outlook.com, and all our engineering investments are in that space.  We are not investing in our legacy SOAP API – Exchange web services, and associated client libraries. 

That's all very well but the only java sdk for Graph is an Android SDK. I've raised a question about the plain Java SDK at https://github.com/microsoftgraph/msgraph-sdk-android/issues/60 and plain Java SDK is apparently months away. 

Microsoft seem to be massively under-resourced and under-committed for supporting platforms outside of DotNet. Disappointing.

**Comment by davster** [comment]
Thanks for the input.  While we don't have a concrete timeline right now for delivery, we currently have a REST java SDK in process.

**Comment by madmuffin1** [comment]
If am I understanding this correctly, the Graph Java SDK has been released here: https://github.com/microsoftgraph/msgraph-sdk-java

**Comment by davidmoten** [comment]
Graph is terrible for email, use EWS:

https://stackoverflow.com/questions/50692280/send-reference-attachment-to-email-via-graph-api

and 

https://github.com/microsoftgraph/msgraph-sdk-java/issues/21

**Comment by serious6** [comment]
_Ref. #661_
