### ISSUE TITLE
谁能帮下忙

### ISSUE THREAD

**Issue by hui66** [OfficeDev/ews-java-api#638]
在发送的时候，显示一个或多个收件人无效
代码：
  mailMessage message = new EmailMessage(service);
// 邮件主题
message.Subject = "Hello kevindiao!";
message.Body=new MessageBody();
// 指定发送邮件的格式，可以是Text和Html格式
message.Body.BodyType=BodyType.Text;
// 邮件内容
message.Body.Text = "Sent using the EWS Managed API.";
// 可以添加多个邮件人.也可以添加一个集合，用
// message.ToRecipients.AddRange(IList toEmailAddress_list)
message.ToRecipients.Add("test@klx168.com");
//报错，显示一个或者多个发送人无效
message.send()

**Comment by coooliang** [comment]
你是怎么连接邮箱服务器的呢？

**Comment by hui66** [comment]
邮箱服务器吗？不是有官方提供的api吗？自己去看下吧，很简单的

**Comment by hui66** [comment]
现在的话过年手边没电脑，也没办法回答你

**Comment by hui66** [comment]
像csdn上面去找下，你这种问题一般都能解决的

**Comment by coooliang** [comment]
`ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP1); // 新建server版本
		ExchangeCredentials credentials = new WebCredentials("username", "password"); // 自己的用户名和密码
		service.setCredentials(credentials);
		service.setUrl(new URI("https://mail.xxx.com/EWS/Exchange.asmx")); // mail.TESTMAIL.com
																						// 改为自己的邮箱
		// EmailMessage msg= new EmailMessage(service);
		// msg.setSubject("Hello world!"); //主题
		// msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Managed API."));
		// //内容
		// msg.getToRecipients().add("61917380@qq.com"); //收件人
		// msg.getCcRecipients().add("test2@test.com"); //抄送人
		// msg.getAttachments().addFileAttachment("D:\\Downloads\\EWSJavaAPI_1.2\\EWSJavaAPI_1.2\\Getting started with EWS Java API.RTF");
		// //附件
		// msg.send(); //发送

		// 创建过滤器
		Folder inbox = Folder.bind(service, WellKnownFolderName.Inbox);
		// 创建过滤器条件，查询10封邮件
		ItemView view = new ItemView(10);

		// 查询
		FindItemsResults<Item> findResults = service.findItems(inbox.getId(), view);

		for (Item item : findResults.getItems()) {
			EmailMessage message = EmailMessage.bind(service, item.getId());
			System.out.println("发件人: " + message.getSender());
			System.out.println("标题: " + item.getSubject());
			MessageBody body = message.getBody();
			String bodyHTML = MessageBody.getStringFromMessageBody(body);
			System.out.println(bodyHTML);
		}`

**Comment by coooliang** [comment]
`ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP1); // 新建server版本
		ExchangeCredentials credentials = new WebCredentials("username", "password"); // 自己的用户名和密码
		service.setCredentials(credentials);
		service.setUrl(new URI("https://mail.xxx.com/EWS/Exchange.asmx")); // mail.TESTMAIL.com
																						// 改为自己的邮箱
		EmailMessage msg= new EmailMessage(service);
		msg.setSubject("Hello world!"); //主题
		msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Managed API."));
		//内容
		msg.getToRecipients().add("61917380@qq.com"); //收件人
		msg.getCcRecipients().add("test2@test.com"); //抄送人
		msg.getAttachments().addFileAttachment("D:\\Downloads\\EWSJavaAPI_1.2\\EWSJavaAPI_1.2\\Getting started with EWS Java API.RTF");
		//附件
		msg.send(); //发送

		
		
		
		// 创建过滤器
		Folder inbox = Folder.bind(service, WellKnownFolderName.Inbox);
		// 创建过滤器条件，查询10封邮件
		ItemView view = new ItemView(10);

		// 查询
		FindItemsResults<Item> findResults = service.findItems(inbox.getId(), view);
		for (Item item : findResults.getItems()) {
			EmailMessage message = EmailMessage.bind(service, item.getId());
			System.out.println("发件人: " + message.getSender());
			System.out.println("标题: " + item.getSubject());
			MessageBody body = message.getBody();
			String bodyHTML = MessageBody.getStringFromMessageBody(body);
			System.out.println(bodyHTML);
		}`

**Comment by coooliang** [comment]
`ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP1); // 新建server版本
		ExchangeCredentials credentials = new WebCredentials("username", "password"); // 自己的用户名和密码
		service.setCredentials(credentials);
		service.setUrl(new URI("https://mail.xxx.com/EWS/Exchange.asmx")); // mail.TESTMAIL.com
																						// 改为自己的邮箱
		EmailMessage msg= new EmailMessage(service);
		msg.setSubject("Hello world!"); //主题
		msg.setBody(MessageBody.getMessageBodyFromText("Sent using the EWS Managed API."));
		//内容
		msg.getToRecipients().add("61917380@qq.com"); //收件人
		msg.getCcRecipients().add("test2@test.com"); //抄送人
		//附件
		msg.getAttachments().addFileAttachment("D:\\Downloads\\EWSJavaAPI_1.2\\EWSJavaAPI_1.2\\Getting started with EWS Java API.RTF");
		//发送
		msg.send(); 
		// 创建过滤器
		Folder inbox = Folder.bind(service, WellKnownFolderName.Inbox);
		// 创建过滤器条件，查询10封邮件
		ItemView view = new ItemView(10);

		// 查询
		FindItemsResults<Item> findResults = service.findItems(inbox.getId(), view);
		for (Item item : findResults.getItems()) {
			EmailMessage message = EmailMessage.bind(service, item.getId());
			System.out.println("发件人: " + message.getSender());
			System.out.println("标题: " + item.getSubject());
			MessageBody body = message.getBody();
			String bodyHTML = MessageBody.getStringFromMessageBody(body);
			System.out.println(bodyHTML);
		}`

**Comment by serious6** [comment]
_Closed as not in english_

**Comment by zhiqiangren** [comment]
your language is not java ?
