### ISSUE TITLE
ews-java-api java 9 compatability

### ISSUE THREAD

**Issue by winston32** [OfficeDev/ews-java-api#653]
Hi All,
We recently upgraded our exchangeScheduling application to support java 9.Since then we are not able to sync to exchange services and no exceptions in log as well.
Below is the line of code not working when we are using java9 (same piece of code working with java 8):
       Folder folder = Folder.bind(exchangeService, WellKnownFolderName.Calendar);

Any one faced the same issue? Any work around would be appreciated .

**Comment by avromf** [comment]
Hi,

I have yet to thoroughly test our application (which uses EWS for Java) on Java 9 or 10 but I wonder if it has to do with modules?
By default, the standard Java 9 ships with but does not include any "Java EE" modules.
You can include them by using the following command line argument:
--add-modules=java.se.ee

**Comment by serious6** [comment]
Also please refer to [Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/java/javase/eol-135779.html) as Java 9 has a very limited support frame it is more likely we will start supporting java8 officially and then move to a more major java version later on.
