### ISSUE TITLE
Exchange version Support

### ISSUE THREAD

**Issue by joeyjoker** [OfficeDev/ews-java-api#654]
Hi

We want to develop a new function by using this api. But i worried about the api support for Exchange server version. I want to confirm this api support the Exchange server version.

Thanks

**Comment by OS-JaR** [comment]
Hi @joeyjoker,

which exchange server version should be confirmed?

**Comment by serious6** [comment]
We are providing an enumeration what kind of version should be supported. PLease also note that later exchange versions will still be supported as only the specific new features of this version will not be supported.
