### ISSUE TITLE
OSGi Bundle - Enhance the jar with additional Bundle Infos

### ISSUE THREAD

**Issue by stbischof** [OfficeDev/ews-java-api#660]
Hello,

it would be great is you could enhance the jar with additional Bundle infos / create a OSGi Bundle 
Easiest way is to use the apache-felix "maven-bundle-plugin"

https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html
https://bnd.bndtools.org/tools/felix-maven.html

Tell me if you need some help

**Comment by paul-bjorkstrand** [comment]
This ticket may be a bit old, but I agree that it should be done.

For any maintainer/contributor that wishes, here is an example from [mssql-jdbc]:

https://github.com/microsoft/mssql-jdbc/blob/dev/pom.xml#L439

Side not: a different tool/maven plugin is being emerging as the "standard" for creating bundles:

https://bnd.bndtools.org/

[mssql-jdbc]: https://github.com/microsoft/mssql-jdbc

**Comment by stbischof** [comment]
Use bnd. Yes!!!

Still, i would help and create a PR. But i need a reaction of the mentainer.
