### ISSUE TITLE
Is this api maintained at all?

### ISSUE THREAD

**Issue by henrywright88404** [OfficeDev/ews-java-api#661]
Looking at the last commits and some bugs that have been open for months/years and the number of pull requests I assume this is no longer maintained or kept up to date?

**Comment by OS-JaR** [comment]
Hi, 
I think your apprehension is right. Also commented here:
https://github.com/OfficeDev/ews-java-api/issues/661

Maybe there are a few volunteers to set up an unofficial community fork?

**Comment by henrywright88404** [comment]
it would appear Microsoft abandoned this in favor of [https://dev.office.com/blogs/microsoft-graph-java-sdk-preview-2. ](url)

**Comment by davidmoten** [comment]
I've made a lot of contributions to the new Graph Java SDK and my problem is support for email in the Graph API (not the SDK) is poor. See 

* https://stackoverflow.com/questions/50692280/send-reference-attachment-to-email-via-graph-api
* https://github.com/microsoftgraph/msgraph-sdk-java/issues/90

I may have no option but to use this project (possibly forked). I'm attempting to get an answer about this project from other Microsoft staff and I'll report back if I find out anything. If the project is officially dead it should say so on the README.md.

**Comment by henrywright88404** [comment]
@davidmoten Thanks for your comment and I agree the README.md should say so. Fortunately, I'm just about able to get what I need to do do with this API but have had to butcher some solutions together. 

Next time I know to do a little more research before diving in! 

I look forward to finding out if this is dead or not.

**Comment by OS-JaR** [comment]
Hi,
as already mentioned by @MIchaelMainer  [HERE](https://github.com/OfficeDev/ews-java-api/issues/600) and
[HERE](https://github.com/microsoftgraph/msgraph-sdk-java/issues/90), we should fork this repo as a community project. Any volunteers, who should help with that?

Thanks,
Jan

**Comment by serious6** [comment]
Dear community,
sorry for the downtime of this project. Unfortunately with the last realease (which is long ago) for this API the microsoft part and interaction as well as release planning has come to a minimum. I already approached one of the core architects from these days but without an answer. 
As I would like to push this api to a new version personally as the downtime of this project is depressing. 

I would like to **place a call for action** (as of course all of our time is limited). I will therefore create a new ticket here for planning of the next release. Which from my point of you will be a major update (3.0).
As well I will flag all current pull-requests with tag: "user action required" 

If you are interested to also support a new Version of this api please help in reviewing the current PR if they apply to the following:

- proposed change is suitable under the following conditions:
    - contribution guidelines have been followed
    - documentation is suitable and change is well documented / understandable
    - test cases have been integrated (if not at least a minimum needs to be provided)
    - covers the frame of next planned release or should be integrated (justification needed) see #665
- indication if any present api will be broken and if this change applies to be critical

Once enough indication is given we can remove the given "user action required" label and merge the PR (incl. deployment of new snapshot version).

Cheers and thanks for your support.

**Comment by MIchaelMainer** [comment]
Hello. If you organize a maintained fork of this repo, we can add a statement in the readme that will direct people to the community run fork. EWS is being deemphasized in favor of of the Microsoft Graph API and with that, there will be no support from us on the EWS Java API.

**Comment by davidmoten** [comment]
@MIchaelMainer thanks for the update

**Comment by kentongray** [comment]
@MIchaelMainer @serious6  we're not opposed to being the community fork. we are considering working on OAuth support next and already have merged in a few PRs that we have found useful (as well as submitting them)

http://github.com/iOffice/ews-java-api

**Comment by Kooki** [comment]
Hi @all,
so here we go again. It seems I've to use EWS API frequently in the next time so I/we should think again about an 'official-community-fork'. See #692 for details

Jan
