### ISSUE TITLE
Why is there a private getter but a public setter for the same property?

### ISSUE THREAD

**Issue by ghost** [OfficeDev/ews-java-api#672]
https://github.com/OfficeDev/ews-java-api/blob/7f8793a3faef91a7eb22dae0d9cff8118a66cd24/src/main/java/microsoft/exchange/webservices/data/property/complex/MessageBody.java#L193

https://github.com/OfficeDev/ews-java-api/blob/7f8793a3faef91a7eb22dae0d9cff8118a66cd24/src/main/java/microsoft/exchange/webservices/data/property/complex/MessageBody.java#L202

I'm not trying to be funny. I see that there is another static method `getStringFromMessageBody` that does actually what the getter does, and the toString method actually returns the text or an empty string. Is there some bigger reason/design decision/pattern?

**Comment by philipwhiuk** [comment]
Setting a property directly is quite useful in various cases. Getting the actual value might be deemed less useful. The differently method _might_ currently get the value as is but there's no guarantee based on the name that it doesn't do some reformatting.
