### ISSUE TITLE
Is there any JAVA API for retrieving all the mail boxes from an exchange server (like getsearchablemailboxes)

### ISSUE THREAD

**Issue by perusrikanth** [OfficeDev/ews-java-api#673]

**Comment by perusrikanth** [comment]
How to get all the mail boxes from an exchange server using JAVA API.

**Comment by pavelnt** [comment]
GetSearchableMailboxes operation has appeared in Exchange 2013.
This operation is not added to EWS Java API yet. I'm afraid there is no another way to get mailboxes through API.

**Comment by sunny02chaurasia** [comment]
You can use **EWS Java API** to pull the mail box details from an account.

**Comment by perusrikanth** [comment]
NO EWS Java API found for GetSearchableMailboxes

**Comment by iamdeadman** [comment]
So, what alternatives are there other than the Java API for querying the list of mailboxes. 
I have to setup a cloud service app in which I need to subscribe to push notifications daily for all the mailboxes so I need to be able to query the updated list of mailboxes every time I run the lambda

**Comment by perusrikanth** [comment]
Getting list of mailboxes is available in C#, C++ and PHP
C# - public Microsoft.Exchange.WebServices.Data.GetSearchableMailboxesResponse GetSearchableMailboxes (string searchFilter, bool expandGroupMembership);
C++ - Microsoft::Exchange::WebServices::Data::GetSearchableMailboxesResponse ^ GetSearchableMailboxes(System::String ^ searchFilter, bool expandGroupMembership);
More details at - https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.exchangeservice.getsearchablemailboxes?redirectedfrom=MSDN&view=exchange-ews-api#Microsoft_Exchange_WebServices_Data_ExchangeService_GetSearchableMailboxes_System_String_System_Boolean_

For PHP, refer - https://github.com/jamesiarmes/php-ews
