### ISSUE TITLE
The time zone of the meeting is not consistent

### ISSUE THREAD

**Issue by zhiqiangren** [OfficeDev/ews-java-api#680]
Hi,
I'm trying to create an Appointment and add some attendees, the attendees receive an email,but the content of the meeting automatically  add the start time ,end time and the location.
But the time is in UTC format, which is not consistent with my local time zone.
The detailed results are shown in the figure below,Does anyone have the same problem as me?
![image](https://user-images.githubusercontent.com/30388326/49716625-3b499100-fc8f-11e8-8025-1033479944e8.png)

**Comment by zhiqiangren** [comment]
I'm from China! I need your help.

**Comment by zhiqiangren** [comment]
@itbw @selamialtin This problem has been bothering me for two days, I almost broke down, and then handed it to my partner to solve, he referred to this problem #398  ,we added the following line of code, and we succeeded. Thanks my partner a lot .
`Appointment appointment = new Appointment(service);

				appointment.setSubject(appointParam.getSubject());`  
				MessageBody messageBody = new MessageBody();
				messageBody.setBodyType(BodyType.Text);
				messageBody.setText(appointParam.getRemark().toString());
				appointment.setBody(messageBody);
				appointment.setStartTimeZone(new OlsonTimeZoneDefinition(TimeZone.getTimeZone("Asia/Shanghai")));
	                        appointment.setStart(startDateMidnight);
			        appointment.setEnd(endDateMidnight);`

**Comment by yangziwen12345** [comment]
is there any way to delete  date of auto add

**Comment by zhiqiangren** [comment]
> is there any way to delete date of auto add

@yangziwen12345 Probably not. 
I want to get rid of the generated dates that generated automatically  at first, but I tried a lot of ways, and I failed.

**Comment by yangziwen12345** [comment]
> > 有没有办法删除自动添加的日期
> 
> @ yangziwen12345可能不是。
> 我想摆脱最初自动生成的生成日期，但我尝试了很多方法，但我失败了。

你现在用的是Exchange2007 还是2010

**Comment by zhiqiangren** [comment]
@yangziwen12345  i try both ,but no one cuold satisfy my requirement. this it is.

**Comment by stulife** [comment]
> Hi,
> I'm trying to create an Appointment and add some attendees, the attendees receive an email,but the content of the meeting automatically add the start time ,end time and the location.
> But the time is in UTC format, which is not consistent with my local time zone.
> The detailed results are shown in the figure below,Does anyone have the same problem as me?
> ![image](https://user-images.githubusercontent.com/30388326/49716625-3b499100-fc8f-11e8-8025-1033479944e8.png)这个问题你解决了吗？怎么解决的

**Comment by zhiqiangren** [comment]
I solved it, add this code as below:
`ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2007_SP1); 
		ExchangeCredentials credentials = new WebCredentials(email, password);
		service.setCredentials(credentials);
		try {
			service.setUrl(new URI("xxx/ews/Exchange.asmx"));
		} catch (URISyntaxException e1) {
			e1.printStackTrace();
		}

		SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 
		String startStr = "2018-12-28 17:30:00";
		String endStr = "2018-12-28 18:30:00";
		
		try {
			Appointment meeting = new Appointment(service);
			meeting.setSubject("this is note !");
			meeting.setBody(MessageBody.getMessageBodyFromText("this is the content."));
			
			Date startDate=sdf.parse(startStr);
			Date endDate=sdf.parse(endStr);
			
			meeting.setStartTimeZone(new OlsonTimeZoneDefinition(TimeZone.getTimeZone("Asia/Shanghai")));
			meeting.setStart(startDate);
			meeting.setEnd(endDate);
			
			meeting.setLocation("Beijing Restaurant");
			String[] strEmail = {"renzhiqiang@chamc.com.cn", "773837815@qq.com"};
			for(String str : strEmail) {
				meeting.getRequiredAttendees().add(str);
			}
			meeting.save();
			
		} catch (Exception e) {
			e.printStackTrace();
		}`

the important line is 
`meeting.setStartTimeZone(new OlsonTimeZoneDefinition(TimeZone.getTimeZone("Asia/Shanghai")));`
but the ExchangeVersion must be Exchange2007_SP1;
this is all.

**Comment by stulife** [comment]
@zhiqiangren Thank you

**Comment by zhiqiangren** [comment]
@stulife 你也在做关于outlook方面的二次开发？具体是什么内容？

**Comment by stulife** [comment]
> 在做关于outlook方面的二次开发？具体是什么内容？

嗯，目前做物联网方面，outlook只是其中一小块

**Comment by jyt15838586105** [comment]
删除时 怎么解决时区问题

**Comment by jyt15838586105** [comment]
或者能把这一行去掉也行，这个问题从我来这家公司一直没有解决

**Comment by jyt15838586105** [comment]
qq 1165892587 能解决的q我一下，十分感谢

**Comment by OS-JaR** [comment]
Hi @jyt15838586105,
please use english as main written language, otherwise a lot of members can't help you :-)

Jan
