### ISSUE TITLE
Saving Email to Hard Drive Folder

### ISSUE THREAD

**Issue by server2245** [OfficeDev/ews-java-api#688]
I need JIRA to read emails stored on a local system folder but i don't know which API method will help me to do this.

Currently I am able to read email using below code

EmailMessage emailMessage = EmailMessage.bind(service, itm.getId());

Please advise

**Comment by OS-JaR** [comment]
Hi,

what exactly do you want? `EmailMessage emailMessage = EmailMessage.bind(service, itm.getId());` is the correct way to bind an Exchange Mail by its (EWS)-ID. What do you mean with:
'I need JIRA to read emails stored on a local system folder but i don't know which API method will help me to do this.'

Jan

**Comment by server2245** [comment]
> Hi,
> 
> what exactly do you want? `EmailMessage emailMessage = EmailMessage.bind(service, itm.getId());` is the correct way to bind an Exchange Mail by its (EWS)-ID. What do you mean with:
> 'I need JIRA to read emails stored on a local system folder but i don't know which API method will help me to do this.'
> 
> Jan

Hi Jan, I want to store each email as a text file. How can i do this ?.

**Comment by OS-JaR** [comment]
Hi,
to store an email on local file system you need to handle the 'MimeContent'.
At first you've to load this property:

`EmailMessage emailMessage = EmailMessage.bind(service, new ItemId("MyItemId"), new PropertySet(ItemSchema.Id, ItemSchema.MimeContent))`

As result Exchange will return the MimeContent as byte[]. Then you have to store these bytes into a file:

```
File toSave= new File(".\myfolder\MyItemId.eml");
FileUtils.writeByteArrayToFile(toSave, emailMessage.getMimeContent().getContent());
```

This should do all you want :-)

Jan

**Comment by server2245** [comment]
Hi Jan,

Thanks for the code. But your code gives me below error

microsoft.exchange.webservices.data.core.exception.service.local.ServiceObjectPropertyException: You must load or assign this property before you can read its value

**Comment by server2245** [comment]
Thanks. It worked now. I can store emails as text file.
