### ISSUE TITLE
Extracting Text from HTML Email

### ISSUE THREAD

**Issue by server2245** [OfficeDev/ews-java-api#689]
Is there a direct API method available in ews-java-api to extract only Text from HTML formatted email message?.

**Comment by davster** [comment]
https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/bodytype

Use it with get item

**Comment by OS-JaR** [comment]
Hi,
I think he wants to ask how to only extract text content from HTML mails content only. 
```
<!DOCTYPE html>
<html>
<body>
<h1>My First Heading</h1>
<p>My first paragraph.</p>
Normal Text
</body>
</html>
```

should return something like
```
My First Heading
My first paragraph.
Normal Text
```
As far as I know, this is not possible. 

BodyType.Best does not exists in current java-ews-api. It could help to achieve this, but I don't know how well it'll works with stuff like <ahref> and stuff like that.

Jan

EDIT:

**Comment by davster** [comment]
Thanks for the clarification.  That is what BodyType.Text is intended to do.  From the above link:

"Text >> The response will return an item body as plain text."

Here is another link with some code:
https://stackoverflow.com/questions/11243911/ews-body-plain-text

**Comment by server2245** [comment]
Setting bodytype helped me and it worked. Thanks

**Comment by server2245** [comment]
```
PropertySet PROPERTY_SET_TEXT_BODY = new PropertySet(BasePropertySet.FirstClassProperties,ItemSchema.Body,ItemSchema.Subject,ItemSchema.Attachments);
PROPERTY_SET_TEXT_BODY.setRequestedBodyType(BodyType.Text);
Item itm = Item.bind(service, itemId, PROPERTY_SET_TEXT_BODY);
```
