### ISSUE TITLE
Does ews-java-api have access to the address book?

### ISSUE THREAD

**Issue by novNorthSea** [OfficeDev/ews-java-api#695]
I want to get the contacts of my company in the address book through ews-java-api. But I can't find the interface.

**Comment by pkropachev** [comment]
Do you want to retrieve contacts from Global Address List or from Contacts folder of user?
I'm afraid EWS Java API and EWS managed API don't provide possibility to retrieve contacts from GAL.
There is [EWS operation 'ResolveName'](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/resolvenames-operation), but this operation has restrictions.
You can take a look at [EWS operation 'FindPeople'](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/findpeople-operation) (has been introduced in Exchange 2013). Look at the article ["Using the EWS FindPeople"](https://gsexdev.blogspot.com/2013/05/using-ews-findpeople-operation-in.html).

**Comment by novNorthSea** [comment]
> Do you want to retrieve contacts from Global Address List or from Contacts folder of user?
> I'm afraid EWS Java API and EWS managed API don't provide possibility to retrieve contacts from GAL.
> There is [EWS operation 'ResolveName'](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/resolvenames-operation), but this operation has restrictions.
> You can take a look at [EWS operation 'FindPeople'](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/findpeople-operation) (has been introduced in Exchange 2013). Look at the article ["Using the EWS FindPeople"](https://gsexdev.blogspot.com/2013/05/using-ews-findpeople-operation-in.html).

Yes, I want to retrieve contacts from Global Address List. I've also found the FindPeople Operation in the network requests of Outlook Web App. In the current case, I can use this SOAP api instead. Thanks for answering.

**Comment by GiorgiSheklashvili** [comment]
@novNorthSea Did you solve this problem? Which SOAP api do you mean?

**Comment by pkropachev** [comment]
Raw EWS SOAP API. This is base for EWS Java API / EWS Managed API.
Look at https://exchange-fqdn/EWS/Exchange.asmx or https://outlook.office365.com/EWS/Exchange.asmx. You can generate proxy classes based on Services.wsdl that is provided by Exchange server (on-premise or online). EWS Java API and EWS Managed API are high level libraries (wrappers over raw EWS API).

**Comment by GiorgiSheklashvili** [comment]
@pkropachev thanks
