### ISSUE TITLE
Session expiration

### ISSUE THREAD

**Issue by MieskeB** [OfficeDev/ews-java-api#703]
Can created sessions expire? If so, how do I know?

**Comment by pkropachev** [comment]
What do you mean?

**Comment by MieskeB** [comment]
Well, when you log in, you create a ExchangeSession object. Can this session expire? Like if I keep this session alive for more then a year in memory, can I still send requests?

**Comment by pkropachev** [comment]
I believe you mean `ExchangeService` object.
In fact, creation `ExchangeService` object and setting properties like Credentials or URL don't do anything. You don't create any sessions on Exchange side.
EWS is a stateless web service. The EWS API doesn't maintain an open connection to EWS. A new connection is established every time you make a request, and this connection is closed right after that.

**Comment by MieskeB** [comment]
Ah okay that makes everything a lot clearer thank you!
