### ISSUE TITLE
Can I get the reservation rules for the conference room?

### ISSUE THREAD

**Issue by shibd** [OfficeDev/ews-java-api#704]
hi, Can I get the reservation rules for the conference room?
case:
1. Are Conflict Meetings Permissible
2. Maximum reservation time

ths.

**Comment by shibd** [comment]
@pkropachev

**Comment by shibd** [comment]
help me, tks

**Comment by pkropachev** [comment]
As far as I remember you can check availability, but I'm not sure that booking policy can be obtained using EWS.
