### ISSUE TITLE
OnEvent API is listening twice while receiving every single email in inbox

### ISSUE THREAD

**Issue by Manikandan2101** [OfficeDev/ews-java-api#705]
StreamingSubscription subscription = exchangeService.subscribeToStreamingNotification(folder,EventType.NewMail);
StreamingSubscriptionConnection conn = new StreamingSubscriptionConnection(exchangeService,30);
conn.addSubscription(subscription );
conn.addNotificationEvent(new StreamingsubscriptionConnection.INotificationEventDelegate()){
@Override
public void notificationEventDelegate(object sender, NotificationEventArgs args){
StreamingSubscription subscription = args.getSubscription();
for(NotificationEvent event : args.getEvents()){
if(event instanceof FolderEvent){
FolderEvent folderEvent = (FolderEvent) event;
}
else if (event instanceof ItemEvent){
ItemEvent itemEvent = (ItemEvent) event;
}
else{
logger.error("Unsupported event" + event.getClass)
}

**Comment by Manikandan2101** [comment]
Could you please provide any update for this

**Comment by Manikandan2101** [comment]
@avromf Could you please provide your inputs as this is blocker for us.

**Comment by avromf** [comment]
This sounds vaguely familiar so I looked in the code of my application and found a note I left myself.

```
	// Sometimes we get multiple notifications on the same message, this is used to make sure it doesn't re-process it.
	// As of yet, I haven't figured out how to prevent this from happening in the first place. -avromf
	// This cache is cleared every time it closes or reopens the connection.
```
In other words, I believe it is an outstanding bug and I added a workaround in which I store the id of each message and check against that to make sure I don't process the same message twice.

**Comment by avromf** [comment]
Also see this:
https://github.com/OfficeDev/ews-java-api/issues/75
This indicates it was fixed by #63 
So maybe it was fixed? I think I wrote my workaround before this fix was merged.

**Comment by Manikandan2101** [comment]
@avromf  ,I am not able to understand properly what they did in that issue.Can you tell me how you made that workaround.

**Comment by Manikandan2101** [comment]
@avromf , I have used a global hash map to store the value of the item Id or Internet Id. So I have created a logic like if the id already exist in that hash map the mail will not be sent but the problem with this the hash map getting cleared in the middle of the operation so when the mail is about to send for the second time it checks the condition,since its empty now the id which was added into the old hash map is again added to the new hash map(cleared one) and the mail is getting sent again.

**Comment by avromf** [comment]
In my code, I simply used a set and stored the ids in it, checking against this set every time it got notified about a new email.
I also clear this set every time it reconnects.
As mentioned, I implemented this before the referenced fix was merged into the current API. Maybe my workaround is now unnecessary, or maybe the bug is still not fixed.
